/* ============================================================================
   gentleman-blackbook.js — "The Black Book": an insider's reference for
   Gentleman's Etiquette. Two halves:

     BRAND_CATEGORIES[] — ultra-niche luxury houses across 12 categories
       (watches, tailoring, shoes, leather goods, fragrance, eyewear,
       jewellery, spirits & cigars, grooming, stationery, interiors &
       furniture, shirtmakers) chosen specifically because they're NOT the
       obvious, billboard-famous names — the ones recognised by people
       already deep in a category, not by logo recognition.

     CITIES[] — a worldwide guide (26 hubs across Europe, the Middle East,
       Asia, North & South America, Africa and Oceania), each with one
       insider-leaning pick for Hotel / Restaurant / Event / Holiday.

   This is curated editorial guidance based on reputation and general
   knowledge, not live availability, pricing, or booking data — hours,
   access routes and offerings change, so treat specifics as a starting
   point to verify, not a guarantee. Nothing here is a paid placement.
   ============================================================================ */
(function (root) {
  'use strict';

  var BRAND_CATEGORIES = [
    { key:'watches', label:'Watches', brands:[
      { name:'F.P. Journe', origin:'Geneva, Switzerland', blurb:'The name serious collectors give when asked who they’d buy if money were genuinely no object. Refused mass distribution for two decades before demand caught up with him, not the other way round.' },
      { name:'Philippe Dufour', origin:'Le Sentier, Switzerland', blurb:'Regarded by many watchmakers — not just collectors — as the finest living hand-finisher. Total output has run to single digits a year; owning one is a statement about craft, not display.' },
      { name:'Akrivia (Rexhep Rexhepi)', origin:'Geneva, Switzerland', blurb:'One of the youngest independents to earn the old guard’s respect. Everything is finished in-house, by hand, in a field where most brands outsource that work.' },
      { name:'Kari Voutilainen', origin:'Môtiers, Switzerland', blurb:'A Finnish master known for hand-guilloché dial work most maisons buy in rather than do themselves — the kind of detail only another watchmaker notices first.' },
      { name:'H. Moser & Cie', origin:'Neuchâtel, Switzerland', blurb:'Deliberately blank dials, deliberately anti-marketing — the “Swiss Mad” house that trolls the industry it belongs to and gets away with it because the watchmaking underneath is genuinely serious.' },
      { name:'Naoya Hida & Co.', origin:'Tokyo, Japan', blurb:'An ultra-traditional Japanese independent making watches that look implausibly like 1950s dress pieces. Tiny runs, brutal waiting lists, almost unknown outside serious collector circles.' },
      { name:'Laurent Ferrier', origin:'Geneva, Switzerland', blurb:'Founded by a former Patek Philippe development director after retirement. Output is deliberately tiny; the movements are finished to a standard he refused to compromise on when he went independent.' },
      { name:'Czapek', origin:'Geneva, Switzerland', blurb:'A revived 19th-century Polish-Swiss name, run today by a small, obsessive team — the kind of comeback watchmakers themselves take seriously, rather than a marketing relaunch.' },
    ]},
    { key:'tailoring', label:'Tailoring & Jackets', brands:[
      { name:'Liverano & Liverano', origin:'Florence, Italy', blurb:'The reference point for the soft, high-armhole “Florentine” jacket. Still cut, sewn and pressed entirely on the premises, the old-fashioned way.' },
      { name:'Sartoria Ciardi', origin:'Naples, Italy', blurb:'Third-generation house behind the exaggerated shoulder line that “Neapolitan tailoring” now generally means — copied everywhere, made properly in very few places.' },
      { name:'Solito', origin:'Naples, Italy', blurb:'Founded by a former Rubinacci cutter. Among the last true one-tailor-per-garment ateliers left in a city that used to be full of them.' },
      { name:'Anderson & Sheppard', origin:'Savile Row, London', blurb:'Inventor of the soft “London drape” cut — the reason Fred Astaire and generations of the genuinely well-dressed went there instead of the stiffer houses next door.' },
      { name:'Steed Bespoke', origin:'Savile Row, London', blurb:'Small enough that the cutter who takes your measurements is the same person who finishes your coat — no handoff between rooms, no house style diluted by scale.' },
      { name:'Rubinacci', origin:'Naples, Italy', blurb:'The Neapolitan house that trained a good number of the other names on this list, still family-run three generations in — the root the “Neapolitan tailoring” trend traces back to.' },
      { name:'Sartoria Dalcuore', origin:'Naples, Italy', blurb:'Known among tailoring obsessives for an even softer, more extreme construction than its Neapolitan peers — barely any padding, built to move with the body rather than shape it.' },
      { name:'Cifonelli', origin:'Paris, France', blurb:'A French tailoring house, family-run since 1880, famous for a structured shoulder that bridges English precision and Italian softness — copied by ready-to-wear brands for decades without credit.' },
    ]},
    { key:'shoes', label:'Shoes', brands:[
      { name:'Stefano Bemer', origin:'Florence, Italy', blurb:'Trained under a Ferragamo-schooled master; now the atelier that other insiders quietly send people to when they’ve outgrown ready-to-wear.' },
      { name:'Yohei Fukuda', origin:'Tokyo, Japan', blurb:'Trained in Vienna and Northampton, now considered by many to be making the best lasts of anyone working today — a genuinely global reputation built with almost no marketing.' },
      { name:'Corthay', origin:'Paris, France', blurb:'Pioneered the hand-painted “patina” finish the whole industry now imitates, and still does the real work in France rather than licensing the name out.' },
      { name:'Saint Crispin’s', origin:'Romania', blurb:'A small atelier that quietly makes some of the finest ready-to-wear shoes in the world — the name enthusiasts trade before the big Northampton and Parisian houses.' },
      { name:'Norman Vilalta', origin:'Barcelona, Spain', blurb:'An Argentine-trained cordwainer blending Spanish and English shoemaking traditions into something that doesn’t look like anyone else’s work.' },
      { name:'Gaziano & Girling', origin:'Northampton, England', blurb:'Younger than the historic English names on Northampton’s shoe row, but already spoken of in the same breath by collectors for the sharpness of its lasts.' },
      { name:'Roberto Ugolini', origin:'Florence, Italy', blurb:'Trained at a small Florentine workshop and now one of the few remaining true bespoke-only makers left in the city — no ready-to-wear line to fall back on.' },
    ]},
    { key:'leather', label:'Leather Goods', brands:[
      { name:'Delvaux', origin:'Brussels, Belgium', blurb:'Founded in 1829 — older than Hermès — and still quietly independent. Every bag is signed by the artisan who made it, not just stamped with a house mark.' },
      { name:'Il Bussetto', origin:'Le Marche, Italy', blurb:'Hand-dyed, hand-burnished small leather goods from a workshop most people outside the category have never heard of, and most who know it want to keep it that way.' },
      { name:'Mismo', origin:'Copenhagen, Denmark', blurb:'Scandinavian minimalism applied to bags most fashion editors haven’t caught onto — understated by design, not by accident.' },
      { name:'Equus Leather', origin:'Somerset, England', blurb:'Bridle-leather bags built to outlive their owner, made to order only — no ready stock, no seasonal collections, just a waiting list.' },
      { name:'Bill Amberg', origin:'London, England', blurb:'British saddlery-trained leatherworker whose bags are built for people who’d rather not carry a visible logo at all — quality that announces itself, not a monogram that does.' },
      { name:'Tanner Krolle', origin:'England', blurb:'An 1856-founded English leather house that quietly supplied luggage to old aristocracy long before the big French names turned luggage into a fashion category.' },
    ]},
    { key:'fragrance', label:'Fragrance', brands:[
      { name:'Bogue', origin:'Rome, Italy', blurb:'A one-man Roman perfumery sold through a handful of niche boutiques worldwide — no department store counter, no brand campaign, just the work.' },
      { name:'Areej Le Doré', origin:'United States', blurb:'Small-batch, naturals-heavy perfumery with genuine cult status among collectors — discovered through enthusiast forums, not advertising.' },
      { name:'Slumberhouse', origin:'Portland, Oregon', blurb:'Dense, unconventional compositions built with zero interest in mainstream appeal — polarising by design, which is exactly why the people who love it, love it.' },
      { name:'Bortnikoff', origin:'Ukraine / Russia', blurb:'Painterly, maximalist niche house known almost entirely by word of mouth among people who already own everything else on this list.' },
      { name:'Papillon Artisan Perfumes', origin:'England', blurb:'A single perfumer, Liz Moores, hand-making scents in tiny batches — cult-followed inside fragrance-collector circles and essentially invisible outside them.' },
      { name:'Bruno Fazzolari', origin:'San Francisco, USA', blurb:'An artist-perfumer whose work gets discussed in the same terms as fine art rather than sold at any department store counter.' },
    ]},
    { key:'eyewear', label:'Eyewear', brands:[
      { name:'Cubitts', origin:'London, England', blurb:'Bespoke eyewear with hand-finished acetate, made in small enough batches that most opticians never stock it — you go to them, not the other way round.' },
      { name:'Algha Works', origin:'London, England', blurb:'Makers of genuine gold-wire frames since 1919, still supplying components to legacy eyewear houses worldwide who quietly rely on them.' },
      { name:'Native Sons', origin:'Los Angeles, USA', blurb:'Small-run, Japan-made frames favoured by people who’ve already worn out the obvious designer names and want something with no logo at all.' },
      { name:'Anne et Valentin', origin:'France', blurb:'An architect-founded house doing genuinely original frame engineering, away from the big licensing conglomerates that make most “designer” glasses.' },
      { name:'L.G.R', origin:'Italy', blurb:'Hand-made sunglasses using vintage manufacturing techniques, favoured by people who’ve moved past the obvious designer sunglasses years ago.' },
    ]},
    { key:'jewellery', label:'Jewellery & Cufflinks', brands:[
      { name:'Hemmerle', origin:'Munich, Germany', blurb:'Fourth-generation family jeweller known for mixing unconventional materials — iron, bronze — with precious stones. Famously doesn’t advertise; the reputation travels on its own.' },
      { name:'JAR (Joel Arthur Rosenthal)', origin:'Paris, France', blurb:'Arguably the most secretive serious jeweller working today — no boutique signage, sales by appointment and existing relationship only.' },
      { name:'Wallace Chan', origin:'Hong Kong', blurb:'A self-taught master carver who invented his own gem-cutting technique. Treated by collectors as a fine artist who happens to work in stone and metal.' },
      { name:'Deakin & Francis', origin:'Birmingham, England', blurb:'Sixth-generation cufflink and small-jewellery maker — the name insiders reach for over the obvious fashion-house cufflinks everyone else defaults to.' },
      { name:'Bhagat', origin:'Mumbai, India', blurb:'A private jeweller working almost entirely by referral for serious collectors of coloured stones — no storefront to walk into.' },
    ]},
    { key:'spirits', label:'Spirits & Cigars', brands:[
      { name:'Gordon & MacPhail', origin:'Speyside, Scotland', blurb:'An independent bottler holding some of the oldest whisky casks in existence — known to serious collectors long before most of the famous distillery names became famous.' },
      { name:'The Scotch Malt Whisky Society', origin:'Edinburgh, Scotland', blurb:'A members-only bottler that labels casks with cryptic numbers instead of brand names, deliberately sidestepping the recognisable labels entirely.' },
      { name:'Chateau de Laubade', origin:'Armagnac, France', blurb:'Family-owned since 1870 — the connoisseur’s answer to the far more famous Cognac houses, from the region that arguably does it better.' },
      { name:'A.E. Dor', origin:'Cognac, France', blurb:'One of the last genuinely family-run Cognac houses still holding old reserve stock rather than having been absorbed into a conglomerate.' },
      { name:'Berry Bros. & Rudd (own casks)', origin:'London, England', blurb:'Britain’s oldest wine and spirits merchant, est. 1698, bottling small-batch whisky and rum under its own name — the trade’s trade, away from big distillery marketing.' },
    ]},
    { key:'grooming', label:'Grooming & Barbering', brands:[
      { name:'Truefitt & Hill', origin:'London, England', blurb:'The world’s oldest barbershop, established 1805, holding a royal warrant — the reference point every modern “gentleman’s barbershop” has since copied.' },
      { name:'D.R. Harris', origin:'London, England', blurb:'Apothecary-grade grooming products still made to nearly unchanged Victorian formulas, sold from the same kind of shop they always were.' },
      { name:'Officina Profumo-Farmaceutica di Santa Maria Novella', origin:'Florence, Italy', blurb:'A working pharmacy since 1221. Fragrance and grooming products have been made in the same building for eight centuries.' },
      { name:'Geo. F. Trumper', origin:'London, England', blurb:'An old-school wet-shave specialist — the barbershop insiders send people to before the trendier modern ones open up down the street.' },
      { name:'Castle Forbes', origin:'Aberdeenshire, Scotland', blurb:'Small-batch shaving products made on a real working Scottish estate, by the family that owns it rather than a licensed grooming conglomerate.' },
    ]},
    { key:'stationery', label:'Stationery & Pens', brands:[
      { name:'Visconti', origin:'Florence, Italy', blurb:'Hand-finished fountain pens using resin techniques few other makers still do entirely by hand.' },
      { name:'Onoto', origin:'England', blurb:'Britain’s oldest pen brand, revived by hand-craftspeople rather than relaunched as a mass-production line.' },
      { name:'Il Papiro', origin:'Florence, Italy', blurb:'Hand-marbled paper (marmorizzata) made using a centuries-old technique — the actual source serious stationers still order from.' },
      { name:'Pineider', origin:'Florence, Italy', blurb:'Founded 1774, supplied Napoleon and Shelley among others, and still hand-binds and hand-presses in the same city today.' },
      { name:'J. Herbin', origin:'France', blurb:'One of the oldest ink makers in the world, established 1670, still hand-crafting ink in small batches rather than on an industrial line.' },
    ]},
    { key:'interiors', label:'Interiors & Furniture', brands:[
      { name:'George Smith', origin:'London, England', blurb:'British upholstery made the old way — frame-up, by hand — favoured by interior designers who’d rather their client not recognise the name on the sofa.' },
      { name:'Soane Britain', origin:'London, England', blurb:'Founded by a former Nina Campbell designer; small-batch British-made furniture and textiles built to be used for decades, not seasons.' },
      { name:'Promemoria', origin:'Milan, Italy', blurb:'A family-run Italian furniture atelier that quietly supplies interior designers rather than chasing retail showroom presence.' },
      { name:'Pinch', origin:'London, England', blurb:'A husband-and-wife design studio making furniture in small English workshops — designed first, branded a distant second.' },
    ]},
    { key:'shirts', label:'Shirtmakers', brands:[
      { name:'Emma Willis', origin:'London, England', blurb:'Bespoke shirtmaker to discreet British clients, hand-finished in a small Gloucestershire workshop rather than a Jermyn Street factory floor.' },
      { name:'Charvet', origin:'Paris, France', blurb:'The Place Vendôme shirtmaker with thousands of fabric choices and zero ready-to-wear compromise — old enough and serious enough that it doesn’t need to shout about it.' },
      { name:'Ascot Chang', origin:'Hong Kong', blurb:'A third-generation shirtmaker who built a genuinely global bespoke clientele entirely by referral, with no advertising at all.' },
      { name:'Simone Abbarchi', origin:'Florence, Italy', blurb:'A small artisan shirtmaker working out of Florence’s backstreets, known almost entirely by word of mouth among people who already own bespoke suits.' },
    ]},
  ];

  var CITIES = [
    { key:'london', label:'London', region:'Europe',
      hotel:{ name:'41 (Buckingham Gate)', note:'A discreet 41-room hotel behind an unmarked entrance opposite Buckingham Palace — favoured by those who’d rather not be seen at the obvious address.' },
      restaurant:{ name:'Kitchen Table (Bubbledogs)', note:'A 19-seat counter with no printed menu in advance — one of the hardest bookings in London despite zero flash or fanfare.' },
      event:{ name:'Wimbledon Debenture seats', note:'Permanent, privately-owned seats resold on a legal secondary market — the only way to guarantee the same seat every year without a corporate box.' },
      holiday:{ name:'A private Highland sporting week', note:'Grouse or stalking on a private Scottish estate, arranged through a sporting agent rather than a travel site.' } },
    { key:'paris', label:'Paris', region:'Europe',
      hotel:{ name:'Hôtel Particulier Montmartre', note:'An 18th-century private mansion with five rooms and no sign on the gate — you have to already know it’s there.' },
      restaurant:{ name:'Restaurant David Toutain', note:'One Michelin star that regulars will tell you should have three — still gettable without a black book, for now.' },
      event:{ name:'Le Bal des Débutantes', note:'An invitation-only Paris ball that quietly reintroduced old-world debutante presentations to a modern, international guest list.' },
      holiday:{ name:'The Basque coast (Biarritz / Guéthary)', note:'The surf-and-château alternative to the Riviera that French old money never actually left.' } },
    { key:'milan', label:'Milan', region:'Europe',
      hotel:{ name:'Portrait Milano', note:'A former seminary turned townhouse hotel a street back from the Quad — quieter than the big Milan names.' },
      restaurant:{ name:'Trippa', note:'A no-reservations trattoria specialising in offal that Milan’s fashion and design crowd treats as a genuine local secret.' },
      event:{ name:'Private showroom previews (Salone del Mobile / Fashion Week)', note:'The real business happens in the invitation-only previews before the public days open.' },
      holiday:{ name:'Lake Como, off-season', note:'Spring or autumn on the lake — the villas and gardens without the summer coach parties.' } },
    { key:'florence', label:'Florence', region:'Europe',
      hotel:{ name:'Villa San Michele, Fiesole', note:'A former monastery just outside the centre overlooking the city — chosen over the big-name Florence hotels for its quiet.' },
      restaurant:{ name:'A Chianti producer’s own table', note:'The region’s best meals are rarely in a restaurant at all — ask an agriturismo host for a seat at the family table.' },
      event:{ name:'A private atelier visit', note:'Several Florentine tailoring and shoemaking houses will host serious clients for a fitting and a glass of wine, by introduction.' },
      holiday:{ name:'A bespoke fitting trip', note:'Suits and shoes started on one visit, finished on a return trip months later — Florence as a wardrobe project, not just a city break.' } },
    { key:'geneva', label:'Geneva', region:'Europe',
      hotel:{ name:'La Réserve Genève', note:'Set back on its own lakeside grounds, away from the banking-district hotels everyone else defaults to.' },
      restaurant:{ name:'A private banking club dining room', note:'Not open to the public — but the city’s real business, and its real watch talk, happens at these tables.' },
      event:{ name:'An independent watchmaker’s private viewing', note:'During the big watch fairs, the appointment-only back room matters more than the public hall.' },
      holiday:{ name:'A drive through the watch valleys', note:'Vallée de Joux and Neuchâtel, with atelier visits arranged well in advance.' } },
    { key:'monaco', label:'Monaco', region:'Europe',
      hotel:{ name:'Hôtel Métropole Monte-Carlo', note:'Quieter and more design-forward than the Hôtel de Paris — for those who know Monaco beyond the casino.' },
      restaurant:{ name:'The Monaco Yacht Club dining room', note:'Members and their guests only — the view alone is worth the introduction.' },
      event:{ name:'Monaco Yacht Show VIP preview days', note:'Before the public days open, when the serious buyers and brokers actually do business.' },
      holiday:{ name:'A week based aboard, not ashore', note:'Using Monaco as a mooring point for the wider Riviera by sea, rather than staying in town.' } },
    { key:'newyork', label:'New York', region:'North America',
      hotel:{ name:'The Lowell', note:'A small, quiet Upper East Side house favoured over the big midtown names by people who don’t need a landmark lobby.' },
      restaurant:{ name:'Torrisi (and its successors)', note:'The kind of tasting-menu room that built its reputation on word of mouth, not a review.' },
      event:{ name:'A private-room dinner at an old-school NY club', note:'Several of the city’s traditional members’ clubs still run private dining nights — guest-of-a-member only.' },
      holiday:{ name:'Hudson Valley or Litchfield County', note:'Old New York’s actual weekend-house country — not the Hamptons everyone assumes.' } },
    { key:'tokyo', label:'Tokyo', region:'Asia',
      hotel:{ name:'Hoshinoya Tokyo', note:'A modern ryokan built into a Tokyo office tower — the antidote to the big international lobby hotels.' },
      restaurant:{ name:'A ten-seat sushi counter, by introduction', note:'The genuinely great rooms in Tokyo are rarely the ones with English-language reviews — a regular’s introduction still matters more than a booking app.' },
      event:{ name:'A private sumo stable morning practice', note:'Arranged through a local fixer rather than a tour company — watching a heya train before the city wakes up.' },
      holiday:{ name:'Kanazawa over Kyoto', note:'A beautifully preserved historic city without the crowds Kyoto now draws.' } },
    { key:'hongkong', label:'Hong Kong', region:'Asia',
      hotel:{ name:'The Upper House', note:'Design-led and comparatively discreet against the harbour-view giants next door.' },
      restaurant:{ name:'A dai pai dong pointed out by a local', note:'Open-air street kitchens that often outcook the Michelin rooms two streets over — you need someone who already knows which one.' },
      event:{ name:'A private members’ evening at the Hong Kong Jockey Club', note:'Racing as the city’s actual social network, not just a sport.' },
      holiday:{ name:'A junk boat weekend, outlying islands', note:'The local answer to a yacht charter, at a fraction of the fuss and cost.' } },
    { key:'dubai', label:'Dubai', region:'Middle East',
      hotel:{ name:'Al Maha, a Ritz-Carlton Reserve', note:'A desert resort an hour from the city rather than another tower on the Marina.' },
      restaurant:{ name:'A private majlis dinner with a local family', note:'The real Emirati hospitality tradition — not on any booking platform, extended by introduction.' },
      event:{ name:'Camel racing at dawn, Al Marmoom track', note:'Free, public, and almost entirely un-touristed — go before sunrise.' },
      holiday:{ name:'A guided crossing of the Empty Quarter', note:'A multi-day traverse of the Rub’ al Khali with a proper desert guide, rather than a one-hour dune-bashing tour.' } },
    { key:'rome', label:'Rome', region:'Europe',
      hotel:{ name:'J.K. Place Roma', note:'A small townhouse hotel near the Spanish Steps, deliberately residential-feeling rather than a grand hotel lobby.' },
      restaurant:{ name:'Retrobottega', note:'A young, ingredient-driven kitchen locals talk about more than tourists do — no tablecloths, no ceremony, real technique.' },
      event:{ name:'A private after-hours palazzo opening', note:'Several of Rome’s smaller Renaissance palazzo museums can be opened for a private evening viewing through a well-connected fixer.' },
      holiday:{ name:'A bespoke tailoring trip', note:'Rome’s sartoria scene is quieter than Naples’ but no less serious — a fitting trip built around the city rather than the obvious sights.' } },
    { key:'vienna', label:'Vienna', region:'Europe',
      hotel:{ name:'Das Triest', note:'A converted 18th-century stable block designed by Terence Conran — discreet compared to the grand hotels lining the Ringstrasse.' },
      restaurant:{ name:'Steirereck', note:'Regularly rated among the best restaurants in the world, yet still primarily a locals’ destination rather than a tourist stop.' },
      event:{ name:'A subscriber’s box at the Vienna State Opera', note:'Season box-holders can bring guests to a seat no public ticket window sells.' },
      holiday:{ name:'The Salzkammergut lake district', note:'Old Austrian aristocracy’s actual holiday country, an hour or two from Vienna and a world away from it.' } },
    { key:'zurich', label:'Zurich', region:'Europe',
      hotel:{ name:'Storchen Zürich', note:'On the river, family-run for generations, favoured by locals over the big international chains along the lake.' },
      restaurant:{ name:'Kronenhalle', note:'A genuine Zurich institution where the art on the walls — real Picassos, Chagalls, Mirós — was paid for by artists settling their bar tabs.' },
      event:{ name:'A private preview before a major watch or art auction', note:'Zurich’s smaller, serious auction houses run appointment-only previews before the public sale.' },
      holiday:{ name:'A base for the Swiss watch valleys', note:'Zurich as the practical hub for reaching Vallée de Joux, Neuchâtel and private banking meetings alike.' } },
    { key:'madrid', label:'Madrid', region:'Europe',
      hotel:{ name:'Hotel Orfila', note:'An 1886 townhouse near Chueca, deliberately small and residential rather than another grand Gran Vía address.' },
      restaurant:{ name:'Casa Lucio', note:'A genuinely old-Madrid table that Madrileños themselves still book, not a tapas bar built for visitors.' },
      event:{ name:'A members’ evening at Casino de Madrid', note:'A grand 19th-century private society — not a gambling casino in the modern sense — largely unknown to visitors.' },
      holiday:{ name:'Extremadura’s dehesa jamón country', note:'Touring the pasture farms where real ibérico ham is actually produced, rather than the tourist-facing tapas-bar version of it.' } },
    { key:'berlin', label:'Berlin', region:'Europe',
      hotel:{ name:'Hotel de Rome', note:'A former bank headquarters turned hotel, architecturally serious and quieter than the big chain names near the Brandenburg Gate.' },
      restaurant:{ name:'Rutz', note:'An unassuming shopfront hiding one of Germany’s most awarded wine and tasting-menu rooms.' },
      event:{ name:'A private studio visit with a gallery artist', note:'Arranged directly through a Berlin gallery rather than attending a public opening.' },
      holiday:{ name:'The Uckermark lake country', note:'Where wealthy Berliners actually go to disappear for the weekend, north of the city and largely undiscovered by visitors.' } },
    { key:'stockholm', label:'Stockholm', region:'Europe',
      hotel:{ name:'Ett Hem', note:'A converted 1910 townhouse with only 12 rooms, run more like a private home than a hotel.' },
      restaurant:{ name:'Frantzén', note:'One of the hardest tables to get in Europe — a converted 18th-century building with a handful of seats and a years-long reputation to match.' },
      event:{ name:'A private midsummer celebration on the archipelago', note:'By invitation from a local family on one of the islands, rather than any public event in the city.' },
      holiday:{ name:'Sailing the Stockholm archipelago', note:'A week among the 30,000 islands rather than staying in the city itself.' } },
    { key:'edinburgh', label:'Edinburgh', region:'Europe',
      hotel:{ name:'Prestonfield House', note:'A 17th-century manor on the edge of the city, deliberately old-world against the modern hotels on Princes Street.' },
      restaurant:{ name:'The Kitchin', note:'A genuinely serious “nature to plate” kitchen run by a local chef, not a Royal Mile spot built for the festival crowds.' },
      event:{ name:'A private tasting at a working distillery', note:'Arranged directly with a Speyside or Islay distillery rather than through a coach-tour operator.' },
      holiday:{ name:'Highland sporting trips from Edinburgh', note:'Grouse, stalking or salmon on a private estate, arranged through a sporting agent as a base from the city.' } },
    { key:'singapore', label:'Singapore', region:'Asia',
      hotel:{ name:'The Warehouse Hotel', note:'A converted 1895 spice warehouse on the river, quieter and more residential than the big integrated resorts.' },
      restaurant:{ name:'A hawker stall pointed out by a local', note:'Several genuinely outclass the fine-dining rooms at a fraction of the ceremony — you need someone who already knows which one.' },
      event:{ name:'A members’ evening at The Straits Clan', note:'A modern private members’ club in a restored Chinatown shophouse, guest-of-a-member only.' },
      holiday:{ name:'A weekend on Bintan', note:'A short ferry to the nearby Indonesian island that Singaporeans themselves treat as their actual weekend escape.' } },
    { key:'losangeles', label:'Los Angeles', region:'North America',
      hotel:{ name:'San Vicente Bungalows', note:'A members’-club-and-hotel hybrid with a strict no-photos policy — discretion as the entire point, not a marketing line.' },
      restaurant:{ name:'Dan Tana’s', note:'An old-school Hollywood favourite that has never once advertised and doesn’t need to — regulars have been regulars for decades.' },
      event:{ name:'A private studio-lot screening', note:'Arranged through industry contacts in a real working screening room, not a public premiere.' },
      holiday:{ name:'Ojai or the Santa Ynez Valley', note:'LA’s quiet wine-country retreat that isn’t Napa and isn’t trying to be.' } },
    { key:'buenosaires', label:'Buenos Aires', region:'South America',
      hotel:{ name:'Home Hotel Buenos Aires', note:'A small, design-led boutique in Palermo, chosen over the grand palace hotels for its scale and quiet.' },
      restaurant:{ name:'A parrilla recommended by a local butcher', note:'The real steakhouse recommendation chain runs through the meat trade, not a tourist “best of” list.' },
      event:{ name:'A private polo match at a Campo Argentino estancia', note:'By invitation only — Argentine polo’s serious matches are rarely open to the general public.' },
      holiday:{ name:'A week on a Pampas estancia', note:'Horsemanship and asado on a working ranch, rather than another week in the city.' } },
    { key:'capetown', label:'Cape Town', region:'Africa',
      hotel:{ name:'Ellerman House', note:'A small clifftop mansion above Bantry Bay, quieter and more private than the big waterfront hotels.' },
      restaurant:{ name:'A braai hosted at a Cape wine estate', note:'The real local version of a restaurant reservation — an invitation to a farm braai rather than a table in the city.' },
      event:{ name:'A private cellar tasting, small Stellenbosch estate', note:'A family-run producer’s own cellar rather than the big-name wineries on the tour-bus circuit.' },
      holiday:{ name:'A self-drive along the Garden Route', note:'Small guesthouses strung along the coast, in place of one big resort stay.' } },
    { key:'marrakech', label:'Marrakech', region:'Africa',
      hotel:{ name:'A small riad in the medina', note:'A handful of rooms behind an unmarked door, rather than one of the big resort compounds outside town.' },
      restaurant:{ name:'A home-cooked meal in a private riad', note:'Arranged through a local fixer — the real Marrakchi cooking happens in homes, not on restaurant menus.' },
      event:{ name:'A guided evening off the main Djemaa el-Fna square', note:'The quieter side streets and smaller squares, with a local guide who knows which stalls and musicians are worth the detour.' },
      holiday:{ name:'A multi-day trip into the Atlas Mountains', note:'Berber villages and mountain guesthouses, well beyond the city itself.' } },
    { key:'shanghai', label:'Shanghai', region:'Asia',
      hotel:{ name:'The Middle House', note:'A design-led hotel in the former French Concession, quieter and more residential than the Bund’s grand hotels.' },
      restaurant:{ name:'A speakeasy-style Huaiyang restaurant', note:'Tucked into the former French Concession, found by introduction rather than a listing.' },
      event:{ name:'A private viewing at a small French Concession gallery', note:'Independent galleries rather than the major museum openings everyone already knows about.' },
      holiday:{ name:'A weekend in Suzhou’s classical gardens', note:'An hour from Shanghai — the genteel, unhurried counterpoint to the city’s pace.' } },
    { key:'seoul', label:'Seoul', region:'Asia',
      hotel:{ name:'The Shilla’s older, more discreet wing', note:'Favoured over the newer glass towers by those who know the property well.' },
      restaurant:{ name:'A hanwoo omakase counter in Gangnam', note:'Korean beef at a counter that takes reservations by word of mouth rather than an app.' },
      event:{ name:'A private tea ceremony in a restored Bukchon hanok', note:'Arranged through a cultural fixer in one of the traditional houses in the Bukchon hanok village.' },
      holiday:{ name:'The Boseong tea fields or Jeju’s west coast', note:'Away from the main tourist circuit on both counts.' } },
    { key:'sydney', label:'Sydney', region:'Oceania',
      hotel:{ name:'The Old Clare Hotel', note:'A converted brewery, design-led and discreet against the big harbour-view names.' },
      restaurant:{ name:'A chef’s-counter omakase in Potts Point', note:'Small enough that it’s known mainly to locals rather than appearing on visitor itineraries.' },
      event:{ name:'A members’ evening at the Australian Club', note:'One of Sydney’s oldest private clubs, guest-of-a-member only.' },
      holiday:{ name:'The Southern Highlands or Hunter Valley', note:'Sydney’s quiet wine-country escape, well away from the coastal tourist run.' } },
    { key:'mexicocity', label:'Mexico City', region:'North America',
      hotel:{ name:'Círculo Mexicano', note:'A converted 1930s building in the historic centre, minimalist and quiet against the big international names in Polanco.' },
      restaurant:{ name:'A market-stall taco counter, chef-recommended', note:'Picked by a local chef rather than a “best tacos” listicle — the real hierarchy runs through the trade, not the guidebooks.' },
      event:{ name:'A private mezcal tasting with a small Oaxacan producer', note:'A family producer’s own selection, arranged directly rather than a bar’s tasting flight.' },
      holiday:{ name:'San Miguel de Allende', note:'Colonial Mexico’s quieter counterpart to the coastal resorts, a few hours from the city.' } },
  ];

  root.BLACKBOOK_DATA = {
    BRAND_CATEGORIES: BRAND_CATEGORIES,
    CITIES: CITIES,
    catById: function (key) { for (var i=0;i<BRAND_CATEGORIES.length;i++) if (BRAND_CATEGORIES[i].key===key) return BRAND_CATEGORIES[i]; return null; },
    cityById: function (key) { for (var i=0;i<CITIES.length;i++) if (CITIES[i].key===key) return CITIES[i]; return null; },
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = root.BLACKBOOK_DATA;
})(typeof window !== 'undefined' ? window : this);
