/* ============================================================================
   learning-history.js — History engine for the Learning Centre. Curated
   question banks across Ancient Civilisations, Medieval History, Early
   Modern History, Modern History, 20th Century World and Historical Skills
   (sources/causation/interpretation), a 60-level system, placement test,
   Quick Test support and a Timeline & Key Events reference library.
   Consumed by the DC logic class via window.LearningHistory.
   ============================================================================ */
(function (root) {
  // Runs once: the <helmet> relocation re-executes every script. See engine-guards.test.mjs.
  if (root.LearningHistory) return;

  'use strict';
  function ri(a, b) { return a + Math.floor(Math.random() * (b - a + 1)); }
  function pick(arr) { return arr[ri(0, arr.length - 1)]; }
  function shuffle(arr) { var a = arr.slice(); for (var i = a.length - 1; i > 0; i--) { var j = ri(0, i); var t = a[i]; a[i] = a[j]; a[j] = t; } return a; }

  var ANCIENT = [
    { level: 3, q: 'Which river valley civilisation built the pyramids?', a: 'Ancient Egypt', d: ['Ancient Egypt', 'Ancient Rome', 'Ancient Greece', 'Mesopotamia'], why: 'Ancient Egyptian pharaohs built the pyramids as monumental tombs along the Nile.' },
    { level: 6, q: 'What system of government did Ancient Athens pioneer?', a: 'Democracy', d: ['Democracy', 'Monarchy', 'Feudalism', 'Theocracy'], why: 'Athens developed one of the earliest forms of democracy, with citizens voting directly on laws.' },
    { level: 9, q: 'What was the Roman system of roads and law primarily used for?', a: 'Governing and connecting a vast empire', d: ['Governing and connecting a vast empire', 'Religious pilgrimage only', 'Trade with China exclusively', 'Military training only'], why: 'Roman roads and law codes allowed efficient control, trade and communication across their huge empire.' },
    { level: 12, q: 'What writing system did the Ancient Sumerians develop?', a: 'Cuneiform', d: ['Cuneiform', 'Hieroglyphics', 'Latin alphabet', 'Cyrillic'], why: 'Cuneiform, wedge-shaped marks pressed into clay, is one of the earliest known writing systems.' },
    { level: 15, q: 'What was the Silk Road primarily used for?', a: 'Trade between East and West', d: ['Trade between East and West', 'Military invasion routes only', 'Religious pilgrimage only', 'Transporting only spices'], why: 'The Silk Road was a network of trade routes connecting China, Central Asia, the Middle East and Europe.' },
    { level: 4, q: 'Why was the Nile River so important to Ancient Egyptian civilisation?', a: 'Its annual floods made the surrounding land fertile for farming', d: ['Its annual floods made the surrounding land fertile for farming', 'It was used only for religious ceremonies', 'It separated Egypt from all other civilisations', 'It froze every winter, providing building material'], why: 'The Nile’s predictable flooding deposited fertile silt, letting Egypt farm reliably and support a large, stable population.' },
    { level: 7, q: 'What was significant about Hammurabi’s Code in Ancient Babylon?', a: 'It was one of the earliest written law codes, applying rules publicly', d: ['It was one of the earliest written law codes, applying rules publicly', 'It banned all trade with neighbouring states', 'It was a religious text with no legal power', 'It only applied to the royal family'], why: 'Hammurabi’s Code (c.1754 BCE) set out laws and punishments publicly, an early step toward codified justice rather than arbitrary rule.' },
    { level: 10, q: 'Why is the fall of the Western Roman Empire (476 CE) considered historically significant?', a: 'It marked the end of centralised Roman rule in Western Europe, reshaping the continent', d: ['It marked the end of centralised Roman rule in Western Europe, reshaping the continent', 'It had no lasting effect on Europe', 'It immediately created the modern nation-states of Europe', 'It only affected trade with Asia'], why: 'Its collapse fragmented Western Europe into smaller kingdoms, setting the stage for the medieval period that followed.' },
    { level: 13, q: 'What was one major consequence of the spread of Ancient Greek culture (Hellenisation) after Alexander the Great’s conquests?', a: 'Greek language, art and ideas spread across a huge area of the ancient world', d: ['Greek language, art and ideas spread across a huge area of the ancient world', 'All conquered regions lost their own cultures entirely', 'Trade between regions decreased sharply', 'Democracy was abolished everywhere'], why: 'Alexander’s conquests spread Greek culture across the Near East and beyond, blending with local traditions.' },
    { level: 1, q: 'Which ancient civilisation built the Great Wall to defend against northern invasions?', a: 'Ancient China', d: ['Ancient China', 'Ancient Egypt', 'Ancient Rome', 'Ancient Persia'], why: 'Sections of the Great Wall were built by successive Chinese dynasties from as early as the 7th century BCE, later joined and extended under the Qin and Ming dynasties.' },
    { level: 2, q: 'What was distinctive about the ancient Indus Valley civilisation’s cities (e.g. Mohenjo-daro)?', a: 'Advanced urban planning, including drainage systems and standardised bricks', d: ['Advanced urban planning, including drainage systems and standardised bricks', 'No permanent buildings at all', 'Cities built entirely underground', 'Reliance on nomadic herding, not farming'], why: 'Indus Valley cities show remarkably early evidence of grid-planned streets and covered drains, suggesting organised civic administration around 2500 BCE.' },
    { level: 5, q: 'What was the Persian Empire under Cyrus the Great notable for?', a: 'Governing a vast, diverse empire with relative religious tolerance', d: ['Governing a vast, diverse empire with relative religious tolerance', 'Forcing every conquered people to abandon their own religion', 'Having no organised administration at all', 'Existing only as a small city-state'], why: 'Cyrus the Great’s empire (6th century BCE) spanned from Egypt to India and was known for allowing conquered peoples to keep their own customs and religions, an unusually tolerant approach for the time.' },
    { level: 8, q: 'What was the Phoenicians’ most influential lasting contribution to later civilisations?', a: 'An alphabet that influenced the Greek and later Latin alphabets', d: ['An alphabet that influenced the Greek and later Latin alphabets', 'The invention of paper', 'The first standardised coinage', 'The construction of the pyramids'], why: 'The Phoenician alphabet, spread through their extensive Mediterranean trade network, is a direct ancestor of the Greek alphabet and, through it, the Latin alphabet used today.' },
    { level: 11, q: 'Why did the ancient Maya civilisation’s achievements in astronomy and mathematics stand out?', a: 'They developed an accurate calendar system and used the concept of zero independently', d: ['They developed an accurate calendar system and used the concept of zero independently', 'They had no writing system at all', 'They never engaged in agriculture', 'They copied their number system directly from Europe'], why: 'Maya astronomers tracked celestial cycles with striking precision and used a positional number system that included zero, developed independently of the Old World.' },
    { level: 14, q: 'What made the Library of Alexandria historically significant in the ancient world?', a: 'It aimed to collect and preserve a vast body of the ancient world’s written knowledge', d: ['It aimed to collect and preserve a vast body of the ancient world’s written knowledge', 'It was a purely religious building with no books', 'It only ever held Roman military records', 'It was built after the fall of Rome'], why: 'Founded in Ptolemaic Egypt in the 3rd century BCE, the Library of Alexandria became a major centre of scholarship, symbolising the ancient world’s ambition to gather knowledge in one place.' }
    ];
  var MEDIEVAL = [
    { level: 17, q: 'In what year did the Norman Conquest of England take place?', a: '1066', d: ['1066', '1215', '1348', '955'], why: 'William the Conqueror defeated King Harold at the Battle of Hastings in 1066.' },
    { level: 19, q: 'What document did English barons force King John to sign in 1215?', a: 'Magna Carta', d: ['Magna Carta', 'Domesday Book', 'Bill of Rights', 'Treaty of Verdun'], why: 'Magna Carta limited royal power and established that even the king was subject to the law.' },
    { level: 21, q: 'What disease devastated Europe\u2019s population in the mid-1300s?', a: 'The Black Death (bubonic plague)', d: ['The Black Death (bubonic plague)', 'Smallpox', 'Cholera', 'Influenza'], why: 'The Black Death killed an estimated one-third of Europe\u2019s population between 1347-1351.' },
    { level: 24, q: 'What was the feudal system primarily based on?', a: 'Land granted in exchange for loyalty and service', d: ['Land granted in exchange for loyalty and service', 'Democratic elections', 'Free trade between cities', 'Religious conversion'], why: 'Feudalism organised medieval society in a hierarchy: kings granted land to lords in exchange for military service and loyalty.' },
    { level: 27, q: 'What were the Crusades?', a: 'Religious wars between Christians and Muslims for control of the Holy Land', d: ['Religious wars between Christians and Muslims for control of the Holy Land', 'Trade agreements between Europe and Asia', 'Peasant uprisings against taxation', 'Naval expeditions to the Americas'], why: 'The Crusades (11th-13th centuries) were a series of religious wars over control of Jerusalem and the Holy Land.' },
    { level: 18, q: 'Why was the Domesday Book (1086) significant for Norman rule of England?', a: 'It recorded land and resources, letting William assess and tax his new kingdom effectively', d: ['It recorded land and resources, letting William assess and tax his new kingdom effectively', 'It was purely a religious text with no administrative use', 'It listed only the names of Anglo-Saxon nobles who had died', 'It abolished all English laws immediately'], why: 'The Domesday Book was a survey of land ownership and value, allowing William I to govern and tax England systematically.' },
    { level: 20, q: 'What was one major long-term consequence of the Black Death for European society?', a: 'A labour shortage that increased the bargaining power and wages of surviving peasants', d: ['A labour shortage that increased the bargaining power and wages of surviving peasants', 'An immediate collapse of the feudal system with no lasting effects', 'A sudden population boom across Europe', 'The complete end of trade across Europe'], why: 'With so many workers dead, survivors could demand higher wages and better conditions, gradually weakening the rigid feudal hierarchy.' },
    { level: 23, q: 'What was the main purpose of a medieval castle beyond defence?', a: 'A centre of local administration and lordly power', d: ['A centre of local administration and lordly power', 'Purely a religious building', 'A public marketplace with no other function', 'A prison used only for foreign prisoners'], why: 'Castles combined military defence with governing the surrounding land, housing courts, storage and the lord’s household.' },
    { level: 26, q: 'How did the Magna Carta’s significance change over time?', a: 'Though limited in 1215, it later became a symbol of the principle that rulers are bound by law', d: ['Though limited in 1215, it later became a symbol of the principle that rulers are bound by law', 'It was immediately forgotten and had no later influence', 'It gave full democratic rights to all English people in 1215', 'It was only ever relevant to French history'], why: 'Its 1215 clauses mainly protected barons, but later generations reinterpreted it as an early foundation for constitutional and legal rights.' },
    { level: 16, q: 'Who were the Vikings, and what characterised their activity in medieval Europe?', a: 'Scandinavian seafarers who raided, traded and settled across large parts of Europe', d: ['Scandinavian seafarers who raided, traded and settled across large parts of Europe', 'A purely peaceful trading people with no raiding', 'An army that never left mainland Scandinavia', 'A religious order based in Rome'], why: 'From the late 8th century, Viking longships allowed raids, trade and settlement from North America to the Middle East, alongside significant settlement in Britain and Normandy.' },
    { level: 22, q: 'What was the Hundred Years’ War fought over?', a: 'A dynastic dispute over the succession to the French throne', d: ['A dynastic dispute over the succession to the French throne', 'Control of the Holy Land', 'Religious differences between Catholics and Protestants', 'Trade rights in the Mediterranean'], why: 'The conflict (1337-1453) arose from English kings’ claims to the French crown through their Norman and Plantagenet ancestry, sparking intermittent war across more than a century.' },
    { level: 25, q: 'What role did Joan of Arc play in the Hundred Years’ War?', a: 'She led French troops to key victories, inspired by claimed religious visions', d: ['She led French troops to key victories, inspired by claimed religious visions', 'She was an English general who conquered Paris', 'She negotiated the war’s peace treaty as a diplomat', 'She was a queen who ended the war through marriage'], why: 'Joan of Arc rallied French forces at the siege of Orléans in 1429, turning the war’s momentum, before being captured and executed by the English in 1431.' },
    { level: 28, q: 'What was the significance of the Ottoman conquest of Constantinople in 1453?', a: 'It ended the Byzantine Empire and marked a major shift in power in the Eastern Mediterranean', d: ['It ended the Byzantine Empire and marked a major shift in power in the Eastern Mediterranean', 'It had no lasting political effect on the region', 'It marked the founding of the Byzantine Empire', 'It ended all trade between Europe and Asia permanently'], why: 'The fall of Constantinople ended over a thousand years of Byzantine rule and gave the Ottoman Empire control of a crucial trade and strategic crossroads between Europe and Asia.' },
    { level: 29, q: 'What were the Wars of the Roses fought over in 15th-century England?', a: 'Rival claims to the English throne between the houses of Lancaster and York', d: ['Rival claims to the English throne between the houses of Lancaster and York', 'A war between England and Scotland over independence', 'A religious conflict between Catholics and Protestants', 'A trade dispute with the Hanseatic League'], why: 'The Wars of the Roses (1455-1487) were a series of civil wars between two branches of the royal Plantagenet family, eventually ending with the rise of the Tudor dynasty.' },
    { level: 20, q: 'What was a guild in medieval towns?', a: 'An association of craftsmen or merchants that regulated a trade', d: ['An association of craftsmen or merchants that regulated a trade', 'A branch of the royal army', 'A form of medieval currency', 'A type of monastery'], why: 'Guilds set standards, trained apprentices and protected the economic interests of their members, becoming central to the economic and social life of growing medieval towns.' }
    ];
  var EARLY_MODERN = [
    { level: 29, q: 'What period of renewed interest in art, science and classical learning began in Italy?', a: 'The Renaissance', d: ['The Renaissance', 'The Enlightenment', 'The Reformation', 'The Industrial Revolution'], why: 'The Renaissance (14th-17th century) was a cultural rebirth of art, science and classical learning, starting in Italy.' },
    { level: 31, q: 'What movement did Martin Luther start in 1517?', a: 'The Protestant Reformation', d: ['The Protestant Reformation', 'The Renaissance', 'The Counter-Enlightenment', 'The Crusades'], why: 'Luther\u2019s 95 Theses challenged Catholic Church practices, splitting Western Christianity into Catholic and Protestant branches.' },
    { level: 34, q: 'Who is credited with reaching the Americas in 1492 (from a European perspective)?', a: 'Christopher Columbus', d: ['Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan', 'Marco Polo'], why: 'Columbus\u2019s 1492 voyage, funded by Spain, began sustained European contact with the Americas.' },
    { level: 37, q: 'What was the main cause of the English Civil War (1642-1651)?', a: 'Conflict between King Charles I and Parliament over power', d: ['Conflict between King Charles I and Parliament over power', 'A dispute with France over trade', 'A religious war with Scotland alone', 'A rebellion by the nobility against taxation only'], why: 'Tensions over royal authority, taxation and religion led to war between Royalists and Parliamentarians.' },
    { level: 40, q: 'What ideas did Enlightenment thinkers like Locke and Voltaire promote?', a: 'Reason, individual rights and questioning authority', d: ['Reason, individual rights and questioning authority', 'Return to strict religious rule', 'Expansion of absolute monarchy', 'Rejection of scientific method'], why: 'The Enlightenment (17th-18th century) emphasised reason, science, and individual liberty, influencing revolutions in America and France.' },
    { level: 30, q: 'How did the printing press (from the 1440s) change the spread of ideas in Europe?', a: 'It allowed books and ideas to be copied and distributed far faster and more cheaply than before', d: ['It allowed books and ideas to be copied and distributed far faster and more cheaply than before', 'It had little effect since most people could not read', 'It was banned across Europe immediately', 'It only ever printed religious texts'], why: 'The printing press mass-produced texts, spreading Renaissance and Reformation ideas (including Luther’s) far more widely and quickly than hand-copying allowed.' },
    { level: 33, q: 'What was one key result of the Spanish and Portuguese “Age of Exploration”?', a: 'The establishment of new trade routes and colonial empires in the Americas and Asia', d: ['The establishment of new trade routes and colonial empires in the Americas and Asia', 'The complete isolation of Europe from the rest of the world', 'An immediate decline in European wealth', 'The end of all sea trade'], why: 'Voyages by figures like Columbus and da Gama opened new trade routes, but also led to colonisation, exploitation and the transatlantic slave trade.' },
    { level: 36, q: 'Why did King Charles I’s execution in 1649 mark a turning point in English history?', a: 'It was the first time an English monarch was legally tried and executed by his own subjects', d: ['It was the first time an English monarch was legally tried and executed by his own subjects', 'It restored the monarchy to full power immediately', 'It had no lasting political consequences', 'It ended Parliament’s role in government'], why: 'Charles I’s execution asserted that even a king was accountable to the law, a radical challenge to the idea of divine right that briefly established a republic (the Commonwealth).' },
    { level: 39, q: 'What was the main significance of the Glorious Revolution of 1688?', a: 'It established that Parliament, not the monarch alone, held ultimate power in England', d: ['It established that Parliament, not the monarch alone, held ultimate power in England', 'It abolished the monarchy completely', 'It gave France control over England', 'It had no effect on the balance of power'], why: 'The Glorious Revolution replaced James II with William and Mary under conditions (the Bill of Rights) that limited royal power and strengthened Parliament.' },
    { level: 32, q: 'What was significant about Peter the Great’s rule of Russia (late 17th-early 18th century)?', a: 'He modernised Russia’s military, administration and culture along Western European lines', d: ['He modernised Russia’s military, administration and culture along Western European lines', 'He isolated Russia completely from European contact', 'He abolished the Russian monarchy', 'He was the first Russian ruler to convert to Catholicism'], why: 'Peter the Great travelled through Western Europe studying shipbuilding and administration, then imported reforms to modernise Russia’s army, navy, bureaucracy and even social customs.' },
    { level: 35, q: 'What characterised the reign of Louis XIV of France, known as the “Sun King”?', a: 'Absolute monarchy, centralised power, and lavish royal display (e.g. the Palace of Versailles)', d: ['Absolute monarchy, centralised power, and lavish royal display (e.g. the Palace of Versailles)', 'A constitutional monarchy sharing power with an elected parliament', 'The abolition of the French nobility entirely', 'A policy of total religious freedom for all faiths'], why: 'Louis XIV concentrated political power in the monarchy, famously declaring “l’état, c’est moi” (“I am the state”), and used grand building projects like Versailles to display royal authority.' },
    { level: 38, q: 'What was the significance of the American Revolution (1775-1783)?', a: 'Thirteen British colonies won independence, founding the United States on Enlightenment ideals', d: ['Thirteen British colonies won independence, founding the United States on Enlightenment ideals', 'It resulted in the colonies remaining permanently under British rule', 'It was primarily a religious conflict', 'It had no connection to Enlightenment political ideas'], why: 'The American Revolution drew directly on Enlightenment ideas of natural rights and consent of the governed, and its success inspired later revolutionary movements, including in France.' },
    { level: 41, q: 'What was the “Scientific Revolution” of the 16th-17th centuries primarily about?', a: 'A shift toward observation, experiment and mathematical proof over inherited authority', d: ['A shift toward observation, experiment and mathematical proof over inherited authority', 'The invention of the first factories', 'A religious movement rejecting all science', 'The abolition of universities across Europe'], why: 'Figures like Copernicus, Galileo and Newton championed testing ideas against observed evidence and mathematics, challenging inherited Church and classical authority as the basis for understanding the natural world.' },
    { level: 43, q: 'What triggered the outbreak of the French Revolution in 1789?', a: 'A combination of financial crisis, food shortages and resentment of royal and noble privilege', d: ['A combination of financial crisis, food shortages and resentment of royal and noble privilege', 'A sudden foreign invasion of France', 'A dispute over French colonies in Asia', 'An agreement between the king and the nobility to share power peacefully'], why: 'Chronic government debt, poor harvests driving up bread prices, and widespread anger at the privileges of the nobility and clergy combined to trigger the storming of the Bastille and revolution.' },
    { level: 30, q: 'What was triangular trade in the context of the Atlantic slave trade?', a: 'A trade route linking Europe, West Africa and the Americas, including the trade in enslaved people', d: ['A trade route linking Europe, West Africa and the Americas, including the trade in enslaved people', 'A purely European internal trade network', 'Trade limited only to spices from Asia', 'A trade route that never involved the Americas'], why: 'European ships carried goods to West Africa, enslaved people were transported to the Americas, and colonial produce (sugar, cotton, tobacco) was shipped back to Europe, forming a devastating three-legged trade system.' }
    ];
  var MODERN = [
    { level: 42, q: 'What technological shift defined the Industrial Revolution?', a: 'Machine-powered manufacturing (e.g. steam power)', d: ['Machine-powered manufacturing (e.g. steam power)', 'Return to hand-crafted goods', 'Abolition of factories', 'Decline of urban populations'], why: 'The Industrial Revolution (from ~1760) shifted production from hand tools to powered machinery, transforming economies and societies.' },
    { level: 44, q: 'What event triggered the start of World War One in 1914?', a: 'The assassination of Archduke Franz Ferdinand', d: ['The assassination of Archduke Franz Ferdinand', 'The bombing of Pearl Harbor', 'The invasion of Poland', 'The sinking of the Lusitania'], why: 'The assassination of Austria-Hungary\u2019s heir in Sarajevo triggered a chain of alliances that led to WWI.' },
    { level: 46, q: 'What treaty officially ended World War One?', a: 'The Treaty of Versailles', d: ['The Treaty of Versailles', 'The Treaty of Paris', 'The Congress of Vienna', 'The Treaty of Tordesillas'], why: 'Signed in 1919, the Treaty of Versailles imposed harsh terms on Germany, contributing to later WWII tensions.' },
    { level: 48, q: 'What economic disaster began in 1929 and spread worldwide?', a: 'The Great Depression', d: ['The Great Depression', 'The Oil Crisis', 'Hyperinflation in Germany', 'The Dust Bowl only'], why: 'The Wall Street Crash of 1929 triggered the Great Depression, a decade of severe global economic hardship.' },
    { level: 50, q: 'What event began World War Two in Europe in 1939?', a: 'Germany\u2019s invasion of Poland', d: ['Germany\u2019s invasion of Poland', 'The bombing of Pearl Harbor', 'The fall of France', 'The Battle of Britain'], why: 'Germany\u2019s invasion of Poland in September 1939 led Britain and France to declare war on Germany.' },
    { level: 43, q: 'What was one major social consequence of the Industrial Revolution in Britain?', a: 'Rapid urbanisation as people moved to cities for factory work, often into poor conditions', d: ['Rapid urbanisation as people moved to cities for factory work, often into poor conditions', 'A sharp decline in population growth', 'The end of all agricultural work', 'Immediate equal wealth distribution'], why: 'Industrialisation pulled workers into fast-growing, often overcrowded cities, reshaping British society and eventually prompting reform movements.' },
    { level: 45, q: 'Why is the system of alliances often seen as a long-term cause of World War One?', a: 'It meant a conflict between two countries could rapidly drag in their allies, escalating a local dispute into a wider war', d: ['It meant a conflict between two countries could rapidly drag in their allies, escalating a local dispute into a wider war', 'Alliances had no real effect on how the war started', 'Alliances only existed after the war had already begun', 'Alliances guaranteed peace between all European powers'], why: 'The alliance system (e.g. Triple Entente vs Triple Alliance) meant the assassination of Franz Ferdinand triggered a chain reaction of declarations of war.' },
    { level: 47, q: 'How did the Treaty of Versailles contribute to the rise of tension that led to World War Two?', a: 'Its harsh terms (reparations, territorial loss, war guilt) caused resentment in Germany that extremist parties exploited', d: ['Its harsh terms (reparations, territorial loss, war guilt) caused resentment in Germany that extremist parties exploited', 'It was too lenient and left Germany fully satisfied', 'It had no lasting impact on Germany at all', 'It immediately caused a second war within months'], why: 'Many historians see Versailles\u2019 punitive terms as fuelling the economic hardship and national resentment that the Nazi party later exploited.' },
    { level: 49, q: 'What was a key turning point of the Great Depression for government economic policy?', a: 'Governments (e.g. the USA\u2019s New Deal) intervened more directly in the economy to create jobs and stimulate recovery', d: ['Governments (e.g. the USA\u2019s New Deal) intervened more directly in the economy to create jobs and stimulate recovery', 'All governments refused to intervene at all', 'The Depression ended within a few months without any policy response', 'Trade between countries increased rapidly during the Depression'], why: 'Programmes like Roosevelt\u2019s New Deal marked a shift toward greater government involvement in managing economies during crises.' },
    { level: 41, q: 'What was the “Scramble for Africa” in the late 19th century?', a: 'European powers rapidly colonising and dividing up almost the entire African continent', d: ['European powers rapidly colonising and dividing up almost the entire African continent', 'African nations colonising parts of Europe', 'A period when Africa remained entirely free of European control', 'A trade agreement giving Africa full independence'], why: 'Between roughly 1881 and 1914, European powers competed to claim African territory, formalised at the 1884-85 Berlin Conference, with almost no African representation in the decisions.' },
    { level: 45, q: 'What triggered the Russian Revolution of 1917?', a: 'War-weariness, food shortages and widespread anger at Tsarist rule, exploited by revolutionary movements', d: ['War-weariness, food shortages and widespread anger at Tsarist rule, exploited by revolutionary movements', 'A sudden foreign invasion of Russia by Germany', 'A peaceful transition agreed by the Tsar and Parliament', 'An economic boom that destabilised the government'], why: 'Russia’s heavy losses and economic strain in World War One, combined with long-standing inequality, led to the February Revolution and later the Bolshevik seizure of power in October 1917.' },
    { level: 47, q: 'What did the Suffragette movement campaign for in Britain?', a: 'The right for women to vote', d: ['The right for women to vote', 'Higher wages for factory workers', 'The abolition of the monarchy', 'Free universal education'], why: 'Led by figures such as Emmeline Pankhurst, the Suffragettes campaigned, often through direct action, for women’s voting rights, achieved partially in 1918 and fully on equal terms with men in 1928.' },
    { level: 49, q: 'What was the League of Nations, formed after World War One?', a: 'An international organisation intended to prevent future wars through collective diplomacy', d: ['An international organisation intended to prevent future wars through collective diplomacy', 'A military alliance designed to punish Germany further', 'A trade bloc limited to European nations', 'The forerunner of the European Union with a single currency'], why: 'Established in 1920, the League aimed to resolve disputes peacefully and prevent another world war, but its lack of enforcement power and the absence of major powers like the USA limited its effectiveness.' },
    { level: 51, q: 'What was a major cause of the Spanish Civil War (1936-1939)?', a: 'A conflict between the elected Republican government and Nationalist forces led by Franco', d: ['A conflict between the elected Republican government and Nationalist forces led by Franco', 'A war between Spain and Portugal over colonial borders', 'A dispute over Spanish membership of the League of Nations', 'An invasion of Spain by Italy alone, unconnected to internal politics'], why: 'The war pitted the Republican government against General Franco’s Nationalist rebels, becoming a proxy conflict that drew in foreign powers and is often seen as a prelude to World War Two.' }
    ];
  var TWENTIETH_CENTURY = [
    { level: 51, q: 'What was the Cold War primarily a conflict between?', a: 'The USA and the Soviet Union', d: ['The USA and the Soviet Union', 'Britain and France', 'China and Japan', 'Germany and Italy'], why: 'The Cold War (1947-1991) was a period of political and military tension between the US-led West and the Soviet bloc, without direct war between them.' },
    { level: 53, q: 'What wall, built in 1961, symbolised the division of Europe during the Cold War?', a: 'The Berlin Wall', d: ['The Berlin Wall', 'The Great Wall of China', 'Hadrian\u2019s Wall', 'The Atlantic Wall'], why: 'The Berlin Wall physically divided East and West Berlin until it fell in 1989.' },
    { level: 55, q: 'What movement, led by figures like Martin Luther King Jr., fought racial segregation in the USA?', a: 'The Civil Rights Movement', d: ['The Civil Rights Movement', 'The Suffragette Movement', 'The Labour Movement', 'The Prohibition Movement'], why: 'The Civil Rights Movement (1950s-60s) campaigned against racial segregation and for equal rights in the USA.' },
    { level: 57, q: 'What crisis in 1962 brought the USA and USSR close to nuclear war?', a: 'The Cuban Missile Crisis', d: ['The Cuban Missile Crisis', 'The Suez Crisis', 'The Berlin Airlift', 'The Korean War'], why: 'The discovery of Soviet nuclear missiles in Cuba led to a tense 13-day standoff in October 1962.' },
    { level: 59, q: 'In what year did the Berlin Wall fall, symbolising the end of the Cold War?', a: '1989', d: ['1989', '1991', '1975', '1963'], why: 'The Berlin Wall fell in November 1989; the Soviet Union itself dissolved in 1991.' },
    { level: 52, q: 'Why is the Marshall Plan (1948) seen as historically significant?', a: 'US economic aid helped rebuild Western Europe and limited the spread of communism', d: ['US economic aid helped rebuild Western Europe and limited the spread of communism', 'It funded the Soviet Union’s reconstruction', 'It had no real economic effect on Europe', 'It was a purely military alliance with no economic aid'], why: 'The Marshall Plan provided billions in aid to rebuild Western European economies, also serving US strategic interests during the Cold War.' },
    { level: 54, q: 'What was a major consequence of decolonisation after World War Two?', a: 'Many former colonies in Africa and Asia gained independence, reshaping the global political map', d: ['Many former colonies in Africa and Asia gained independence, reshaping the global political map', 'European empires expanded significantly after 1945', 'Decolonisation only affected the Americas', 'It had no impact on international relations'], why: 'Weakened by the war and facing independence movements, European powers gradually lost their colonial empires from the late 1940s onward.' },
    { level: 56, q: 'Why did the Vietnam War (1955–1975) become so controversial, especially in the USA?', a: 'High casualties, unclear goals, and televised coverage fuelled major domestic protest against US involvement', d: ['High casualties, unclear goals, and televised coverage fuelled major domestic protest against US involvement', 'It had unanimous public support throughout its entire length', 'It was fought entirely without US involvement', 'It ended in a swift, decisive victory'], why: 'Extensive media coverage and mounting US casualties turned public opinion against the war, fuelling the wider protest movements of the era.' },
    { level: 58, q: 'What was the significance of Mikhail Gorbachev’s policies of glasnost and perestroika in the late 1980s?', a: 'Greater openness and economic reform in the USSR contributed to the collapse of Soviet communism', d: ['Greater openness and economic reform in the USSR contributed to the collapse of Soviet communism', 'They strengthened strict Soviet censorship', 'They had no impact on the Soviet Union’s stability', 'They immediately restored the Soviet economy to full strength'], why: 'Gorbachev’s reforms opened up criticism of the Soviet system and loosened central control, factors that contributed to the USSR’s collapse in 1991.' },
    { level: 60, q: 'To what extent do historians agree the Cold War ended purely because of Western military pressure?', a: 'Historians disagree — many emphasise internal Soviet economic weakness and reform as much as, or more than, external pressure', d: ['Historians disagree — many emphasise internal Soviet economic weakness and reform as much as, or more than, external pressure', 'All historians agree it was caused solely by US military strength', 'All historians agree the Cold War never really ended', 'There is no historical debate about the Cold War’s end at all'], why: 'This is a genuine, still-debated historical interpretation question — some historians credit Western pressure (e.g. the arms race), others prioritise internal Soviet economic and political failure, and most see a combination of causes.' },
    { level: 51, q: 'What was the Korean War (1950-1953) primarily a conflict between?', a: 'Communist North Korea (backed by China and the USSR) and South Korea (backed by the UN, mainly the USA)', d: ['Communist North Korea (backed by China and the USSR) and South Korea (backed by the UN, mainly the USA)', 'Japan and China over territorial disputes', 'Two rival dynasties within a single unified Korea', 'Britain and France over colonial control of Korea'], why: 'The Korean War was an early and intense Cold War proxy conflict, ending in an armistice that left Korea divided near the original 38th parallel border, a division that persists today.' },
    { level: 54, q: 'What was the “Space Race” a competition between?', a: 'The USA and the Soviet Union, for achievements in space exploration', d: ['The USA and the Soviet Union, for achievements in space exploration', 'Britain and Germany, for the first satellite', 'China and Japan, for the first moon landing', 'A purely private commercial competition with no government involvement'], why: 'Symbolic Cold War prestige, not just science, drove the Space Race, from the USSR’s Sputnik (1957) to the USA’s Apollo 11 Moon landing (1969).' },
    { level: 56, q: 'What was apartheid, ended in South Africa in the early 1990s?', a: 'A legal system of racial segregation and discrimination against the non-white majority', d: ['A legal system of racial segregation and discrimination against the non-white majority', 'A form of government run entirely by elected representatives of all races equally', 'An economic policy with no connection to race', 'A temporary wartime measure lasting only a few years'], why: 'Apartheid (1948-1990s) legally enforced racial segregation in South Africa; its end, symbolised by Nelson Mandela’s release and later election as president, followed decades of resistance and international pressure.' },
    { level: 58, q: 'What was the significance of the founding of the United Nations in 1945?', a: 'It created a new international body aiming to maintain peace and cooperation after the devastation of WWII', d: ['It created a new international body aiming to maintain peace and cooperation after the devastation of WWII', 'It replaced all national governments with a single world government', 'It was formed before World War Two began', 'It had no connection to the League of Nations’ earlier failure'], why: 'Learning from the League of Nations’ weaknesses, the United Nations was designed with a Security Council holding real enforcement power among the victorious wartime allies, aiming for a more effective peacekeeping body.' },
    { level: 60, q: 'How do historians generally assess the long-term impact of decolonisation on the modern world map?', a: 'It fundamentally reshaped global politics, though the borders often left by colonial powers caused lasting conflicts', d: ['It fundamentally reshaped global politics, though the borders often left by colonial powers caused lasting conflicts', 'It had no lasting effect on international relations', 'All newly independent nations became stable democracies immediately', 'Colonial powers granted independence with no lasting consequences of any kind'], why: 'This is a live area of historical debate: decolonisation created dozens of new nations, but arbitrary colonial-era borders (often ignoring ethnic and cultural boundaries) are widely cited by historians as a source of ongoing regional conflict.' }
    ];
  var SKILLS = [
    { level: 2, q: 'What is a "primary source" in History?', a: 'Evidence created at the time of the event', d: ['Evidence created at the time of the event', 'A textbook written later', 'A documentary made decades later', 'An encyclopedia entry'], why: 'Primary sources (letters, photos, artefacts) were created during or close to the event being studied.' },
    { level: 5, q: 'What is a "secondary source" in History?', a: 'An account created after the event, often analysing primary sources', d: ['An account created after the event, often analysing primary sources', 'An eyewitness diary', 'An original photograph from the event', 'A government record from that year'], why: 'Secondary sources (history books, documentaries) are created afterward, interpreting or analysing primary evidence.' },
    { level: 8, q: 'What does "causation" mean in historical study?', a: 'Understanding why events happened and their causes', d: ['Understanding why events happened and their causes', 'Memorising exact dates only', 'Listing events in random order', 'Describing what people wore'], why: 'Causation examines the reasons and factors that led to a historical event, often distinguishing long-term and short-term causes.' },
    { level: 11, q: 'Why might two historians interpret the same event differently?', a: 'They may use different sources, evidence, or perspectives', d: ['They may use different sources, evidence, or perspectives', 'One of them must be lying', 'History always has only one correct interpretation', 'Only eyewitnesses can be correct'], why: 'Historical interpretation varies because historians weigh evidence differently and may have different viewpoints or available sources.' },
    { level: 14, q: 'What is meant by a source\u2019s "reliability"?', a: 'How trustworthy or accurate the source is likely to be', d: ['How trustworthy or accurate the source is likely to be', 'How old the source is', 'How long the source is', 'How famous the author is'], why: 'Reliability considers factors like the author\u2019s bias, purpose, and closeness to the event when judging how much to trust a source.' },
    { level: 20, q: 'What is a "long-term cause" of a historical event?', a: 'An underlying factor building up over years or decades', d: ['An underlying factor building up over years or decades', 'The event that happened immediately before', 'A cause that only lasted one day', 'An effect, not a cause'], why: 'Long-term causes are conditions or tensions that build gradually, unlike a short-term "trigger" that sets an event off immediately.' },
    { level: 24, q: 'What is a "trigger" (immediate cause) in historical causation?', a: 'The specific event that sets off a chain of events, on top of existing long-term tensions', d: ['The specific event that sets off a chain of events, on top of existing long-term tensions', 'The very first cause in all of history', 'A cause that had no connection to earlier events', 'The final consequence of an event'], why: 'A trigger is the immediate spark (e.g. the assassination of Franz Ferdinand) that sets existing long-term tensions into motion — it rarely acts alone.' },
    { level: 28, q: 'What does "provenance" mean when assessing a historical source?', a: 'Information about who created the source, when, and why', d: ['Information about who created the source, when, and why', 'How old the paper or object physically is', 'The length of the document', 'Whether the source has been translated'], why: 'Provenance (author, date, purpose, audience) is key to judging why a source says what it says, and how much to trust it for a given enquiry.' },
    { level: 32, q: 'A source is heavily biased in favour of one side. Does this mean it has no historical use?', a: 'No — a biased source can still be very useful for revealing that side’s attitudes or propaganda methods', d: ['No — a biased source can still be very useful for revealing that side’s attitudes or propaganda methods', 'Yes — biased sources should always be discarded entirely', 'Bias only matters for primary sources, not secondary ones', 'Bias makes a source completely reliable'], why: 'This is a key GCSE Higher-tier distinction: utility is not the same as reliability — a propaganda poster is unreliable for facts, but highly useful evidence of the attitudes it was designed to promote.' },
    { level: 36, q: 'What is the difference between a source’s "reliability" and its "utility" for an enquiry?', a: 'Reliability is how trustworthy the content is; utility is how useful the source is for a specific historical question, even if unreliable', d: ['Reliability is how trustworthy the content is; utility is how useful the source is for a specific historical question, even if unreliable', 'They mean exactly the same thing', 'Reliability only applies to secondary sources', 'Utility means how old a source is'], why: 'A source can be low in reliability (biased, inaccurate) but high in utility for a specific purpose — e.g. an unreliable diary is still very useful evidence of one person’s beliefs.' },
    { level: 40, q: 'When comparing two historical interpretations of the same event, what is the MOST likely reason they differ?', a: 'The historians used different evidence, asked different questions, or wrote for different purposes/audiences', d: ['The historians used different evidence, asked different questions, or wrote for different purposes/audiences', 'One historian must always be lying', 'Interpretations can never legitimately differ', 'Only the most recent interpretation can be correct'], why: 'Interpretations differ because historians select, weigh and frame evidence differently — GCSE questions specifically test explaining WHY, not just THAT they differ.' },
    { level: 44, q: 'What is meant by "historical significance"?', a: 'How important an event or person was in terms of the change, impact and importance they caused, judged by criteria', d: ['How important an event or person was in terms of the change, impact and importance they caused, judged by criteria', 'How long ago the event happened', 'How many books have been written about it', 'Whether it is mentioned in every textbook'], why: 'Significance is judged against criteria such as how much change something caused, how many people it affected, and its resonance over time — not just personal opinion.' },
    { level: 48, q: 'What is meant by "change and continuity" when studying a period of history?', a: 'Identifying what altered over time alongside what stayed the same', d: ['Identifying what altered over time alongside what stayed the same', 'Only listing events that changed, ignoring anything unchanged', 'A term that only applies to political history', 'Assuming everything in history always changes at the same rate'], why: 'Good historical analysis considers BOTH what changed and what stayed the same across a period — change is rarely total or evenly paced.' },
    { level: 52, q: 'A student says a source is unreliable "because it is old." Why is this a weak historical argument?', a: 'Age alone doesn’t determine reliability — a source’s closeness to the event, purpose and author matter far more', d: ['Age alone doesn’t determine reliability — a source’s closeness to the event, purpose and author matter far more', 'Old sources are always automatically unreliable', 'It is a strong, sufficient argument on its own', 'Only sources over 500 years old can be unreliable'], why: 'A common GCSE examiner correction: reliability depends on provenance, purpose and corroboration, not simply how old a source is — some ancient sources are highly reliable, some recent ones are not.' },
    { level: 55, q: 'Why might a historian deliberately use multiple sources to answer one enquiry question?', a: 'To cross-reference (corroborate) evidence and build a more balanced, reliable conclusion', d: ['To cross-reference (corroborate) evidence and build a more balanced, reliable conclusion', 'Because a single source is always sufficient', 'To make the essay appear longer only', 'Multiple sources always agree completely, so this is unnecessary'], why: 'Corroboration — checking whether independent sources support or contradict each other — is central to how historians build reliable arguments from imperfect evidence.' },
    { level: 58, q: 'When answering "How far do you agree..." in a GCSE History essay, what is the examiner mainly testing?', a: 'The ability to weigh evidence on both sides and reach a supported, balanced judgement', d: ['The ability to weigh evidence on both sides and reach a supported, balanced judgement', 'Simply picking the "correct" side with no evidence', 'Writing the longest possible answer', 'Listing every fact you know regardless of relevance'], why: '"How far" questions require evaluating multiple factors, considering counter-arguments, and reaching a justified overall conclusion — not just narrating events.' },
    { level: 60, q: 'What is the key difference between explaining the CAUSES of an event and explaining its CONSEQUENCES?', a: 'Causes explain why something happened; consequences explain what resulted from it — and are assessed with different criteria (e.g. importance, reach, duration)', d: ['Causes explain why something happened; consequences explain what resulted from it — and are assessed with different criteria (e.g. importance, reach, duration)', 'Causes and consequences are the same thing described differently', 'Consequences always outweigh causes in every essay', 'Causes only exist in political history, not social history'], why: 'Mixing up cause-and-consequence analysis is a common lower-grade error — GCSE mark schemes reward keeping the two distinct and using appropriate judgement criteria for each.' }
  ];

  var BANKS = { ancient: ANCIENT, medieval: MEDIEVAL, earlymodern: EARLY_MODERN, modern: MODERN, twentiethcentury: TWENTIETH_CENTURY, skills: SKILLS };
  var TOPIC_LABELS = { ancient: 'Ancient Civilisations', medieval: 'Medieval History', earlymodern: 'Early Modern History', modern: 'Modern History', twentiethcentury: '20th Century World', skills: 'Historical Skills' };
  function mcFromEntry(topicLabel, e) { return { type: 'mc', topic: topicLabel, level: e.level, prompt: e.q, options: shuffle(e.d), answer: e.a, method: e.why }; }
  function nearestByLevel(bank, level) { return bank.slice().sort(function (a, b) { return Math.abs(a.level - level) - Math.abs(b.level - level); }); }
  var _rot = {};
  function rr(key, arr) {
    var st = _rot[key];
    if (!st || st.i >= st.order.length || st.order.length !== arr.length) { st = { order: shuffle(arr.map(function (_, i) { return i; })), i: 0 }; _rot[key] = st; }
    return arr[st.order[st.i++]];
  }
  function generateFromBank(poolKey, level, topicLabel) { var near = nearestByLevel(BANKS[poolKey], level || 1); return mcFromEntry(topicLabel, rr(poolKey, near)); }
  function generate(topicKey, level) { return generateFromBank(topicKey, level, TOPIC_LABELS[topicKey]); }

  var POOL_KEYS = ['ancient', 'medieval', 'earlymodern', 'modern', 'twentiethcentury', 'skills'];
  // Historical Skills (source analysis, causation, significance, interpretation) used to
  // drop out of the level bands entirely above level 30, despite being one of the most
  // heavily-marked parts of every real GCSE History paper regardless of which content
  // topics a student studies. It's now content-expanded up to level 60 (see SKILLS above)
  // and kept in every band so it's tested throughout the whole ladder, not just at the start.
  var LEVEL_BANDS = [
    { min: 1, max: 15, pools: ['skills', 'ancient'] },
    { min: 16, max: 30, pools: ['medieval', 'skills'] },
    { min: 31, max: 45, pools: ['earlymodern', 'modern', 'skills'] },
    { min: 46, max: 60, pools: ['modern', 'twentiethcentury', 'skills'] }
  ];
  function bandFor(level) { for (var i = 0; i < LEVEL_BANDS.length; i++) { var b = LEVEL_BANDS[i]; if (level >= b.min && level <= b.max) return b; } return LEVEL_BANDS[LEVEL_BANDS.length - 1]; }
  function generateForLevel(level) { level = Math.max(1, Math.min(60, level || 1)); return generate(pick(bandFor(level).pools), level); }
  function generateLevelSet(n, level) { var out = []; for (var i = 0; i < n; i++) out.push(generateForLevel(level)); return out; }
  function levelLabel(level) { if (level >= 50) return 'GCSE Ready'; if (level >= 40) return 'Advanced'; if (level >= 30) return 'Upper Intermediate'; if (level >= 20) return 'Intermediate'; if (level >= 10) return 'Elementary'; return 'Beginner'; }
  function gradeFromLevel(level) { if (level >= 56) return 9; if (level >= 51) return 8; if (level >= 46) return 7; if (level >= 40) return 6; if (level >= 33) return 5; if (level >= 26) return 4; if (level >= 18) return 3; if (level >= 10) return 2; return 1; }
  function generatePlacementSet(n) { n = n || 16; var out = []; for (var i = 0; i < n; i++) { var level = Math.round(1 + (i / (n - 1)) * 59); out.push(generateForLevel(level)); } return out; }
  function levelFromScore(pct) { return Math.max(1, Math.min(60, Math.round((pct / 100) * 59) + 1)); }
  function strongestWeakest(breakdown) {
    var scored = (breakdown || []).filter(function (b) { return b.total > 0; }).map(function (b) { return { topic: b.topic, acc: b.ok / b.total }; });
    if (!scored.length) return { strongest: '', weakest: '', focusAreas: [] };
    scored.sort(function (a, b) { return b.acc - a.acc; });
    var strongest = scored[0].topic, weakest = scored[scored.length - 1].topic;
    var focusAreas = scored.slice().sort(function (a, b) { return a.acc - b.acc; }).slice(0, 3).map(function (s) { return s.topic; });
    return { strongest: strongest, weakest: weakest, focusAreas: focusAreas };
  }

  var QT_TYPES = [
    { key: 'ancient', label: 'Ancient Civilisations' }, { key: 'medieval', label: 'Medieval History' }, { key: 'earlymodern', label: 'Early Modern History' },
    { key: 'modern', label: 'Modern History' }, { key: 'twentiethcentury', label: '20th Century World' }, { key: 'skills', label: 'Historical Skills' },
    { key: 'mixed', label: 'Mixed History Test' }
  ];
  var QT_DIFFICULTIES = ['Beginner', 'Intermediate', 'GCSE Foundation', 'GCSE Higher', 'Auto'];
  var QT_LENGTHS = [5, 10, 20, 50];
  function qtDifficultyToTier(diff) { return { Beginner: 1, Intermediate: 2, 'GCSE Foundation': 3, 'GCSE Higher': 4 }[diff] || 2; }
  function qtLevelToTier(level) { level = level || 1; if (level <= 15) return 1; if (level <= 30) return 2; if (level <= 45) return 3; return 4; }
  function qtTierToLevel(tier) { return { 1: 8, 2: 23, 3: 38, 4: 52 }[tier] || 23; }
  function qtQuestionForType(typeKey, tier) { var level = qtTierToLevel(tier); var key = typeKey === 'mixed' ? pick(POOL_KEYS) : typeKey; return generate(key, level); }
  function buildQuickTest(typeKey, difficulty, length, userLevel) {
    var tier = difficulty === 'Auto' ? qtLevelToTier(userLevel || 1) : qtDifficultyToTier(difficulty);
    var out = []; for (var i = 0; i < (length || 10); i++) out.push(qtQuestionForType(typeKey, tier));
    return out;
  }
  function generateDailyChallenge(userLevel) {
    var tier = qtLevelToTier(userLevel || 1);
    var mix = POOL_KEYS.concat(['skills', 'modern']);
    var out = []; for (var i = 0; i < 8; i++) out.push(qtQuestionForType(mix[i % mix.length], tier));
    return out;
  }
  function checkAnswer(q, input) {
    var norm = function (s) { return (s || '').toLowerCase().trim().replace(/[^a-z0-9 ]/g, ''); };
    return norm(input) === norm(q.answer);
  }

  var LESSONS = {
    ancient: {
      title: 'Ancient Civilisations',
      intro: 'The earliest civilisations established the foundations of government, writing, law and architecture that shaped everything that followed.',
      origin: 'The study of ancient civilisations as a rigorous discipline (rather than legend or myth) really began with 19th-century archaeology — the decipherment of Egyptian hieroglyphics via the Rosetta Stone (Jean-François Champollion, 1822) and of Mesopotamian cuneiform shortly after opened up direct primary-source access to these societies\u2019 own writing, rather than relying only on later Greek and Roman accounts of them, which were often incomplete or biased.',
      sections: [
        { heading: 'Why Civilisations Cluster Around Rivers', body: 'Ancient Egypt (the Nile), Mesopotamia (the Tigris and Euphrates), the Indus Valley and ancient China (the Yellow River) all developed as major civilisations along major rivers — this isn\u2019t coincidence: rivers provided reliable water for agriculture, naturally fertile flooded soil, and a transport route for trade, all of which allowed large, settled populations (and eventually cities, writing and government) to develop faster than in less hospitable environments.' },
        { heading: 'Athenian Democracy Was Radical — and Limited', body: 'Athenian democracy (from around 508 BCE) was genuinely radical for its time: citizens voted directly on laws rather than through elected representatives, a form called "direct democracy." But it excluded the vast majority of the population living in Athens — women, enslaved people, and foreign residents had no political voice at all — a crucial context that\u2019s essential to understanding both its historical significance and its real limitations compared to how "democracy" is used today.' },
        { heading: 'Rome\u2019s Infrastructure Was a Tool of Control, Not Just Convenience', body: 'Roman roads, aqueducts and legal codes weren\u2019t built primarily for citizens\u2019 comfort — they were deliberate tools for governing and defending an enormous, ethnically diverse empire spanning three continents. Roads let legions move quickly to suppress rebellion or defend borders; a standardised legal code let the same laws apply predictably across vastly different conquered territories — infrastructure AS statecraft, not just engineering achievement.' },
        { heading: 'Writing Systems Enabled Complex Society Itself', body: 'Cuneiform and hieroglyphics didn\u2019t just record history — they made large-scale administration possible in the first place: tracking tax records, trade agreements, legal codes and royal decrees at a scale that oral tradition alone couldn\u2019t reliably manage. This is why the emergence of writing is treated as a defining marker separating "history" (documented) from "prehistory" (undocumented) in archaeological convention.' }
      ],
      misconceptions: [
        { myth: 'Athenian democracy worked essentially like a modern democracy.', reality: 'It excluded women, enslaved people and foreigners entirely — only a minority of Athens\u2019 total population could actually vote.' },
        { myth: 'Ancient civilisations arose randomly, unrelated to their geography.', reality: 'Major early civilisations consistently cluster around major rivers, which provided water, fertile soil and trade routes essential to large settled populations.' },
        { myth: 'Roman roads and law were mainly built for citizens\u2019 convenience.', reality: 'They were primarily tools of imperial control — enabling fast military movement and consistent governance across a vast empire.' }
      ],
      expertNotes: [
        'Archaeologists treat the emergence of writing as the conventional boundary between "prehistory" and "history," since it\u2019s the point documented evidence becomes available.',
        'Historians of democracy specifically caveat Athenian democracy\u2019s exclusions when using it as a founding example, to avoid an inaccurate rosy comparison to modern systems.',
        'Historians studying imperial infrastructure (Roman roads, canals, postal systems) generally analyse it through the lens of administrative control, not just technological achievement.'
      ],
      examples: [{ q: 'What system of government did Athens pioneer?', working: 'Citizens voted directly on laws', answer: 'Democracy' }, { q: 'What writing system did the Sumerians use?', working: 'Wedge-shaped marks pressed into clay', answer: 'Cuneiform' }]
    },
    medieval: {
      title: 'Medieval History',
      intro: 'The medieval period (roughly 500-1500 CE) was shaped by feudalism, religious power, and events like the Black Death that reshaped society.',
      origin: 'The term "Middle Ages" (and the negative "Dark Ages" label sometimes attached to its early centuries) was actually coined by Renaissance scholars centuries later, who saw themselves as reviving classical learning after what they framed as a long, unenlightened gap — modern historians generally reject the "Dark Ages" framing as an oversimplification, since the period saw major legal, architectural (Gothic cathedrals), and institutional developments (early universities), even if classical-style scholarship dipped compared to Rome\u2019s peak.',
      sections: [
        { heading: 'Feudalism Was an Economic and Military Contract', body: 'Feudalism operated as a chain of obligation, not a simple dictatorship: a king granted land (a "fief") to a lord in exchange for military support and loyalty, and that lord in turn granted portions of the land to knights on the same terms, down to peasants who worked the land in exchange for protection. Understanding it as a network of mutual (if deeply unequal) obligations, rather than pure top-down control, explains why the system could destabilise so quickly once one link in the chain (like a massive labour shortage) broke down.' },
        { heading: 'The Black Death Broke Feudalism\u2019s Economic Logic', body: 'The Black Death (1347-1351) killed an estimated third of Europe\u2019s population, and this catastrophic labour shortage inadvertently gave surviving peasants massive new bargaining power — with far fewer workers available, peasants could demand wages or better terms for the first time, directly undermining the feudal assumption of a large, dependent, cheap labour force. This is a striking example of how a purely biological event (plague) triggered a fundamental economic and social shift that no ruler had planned or wanted.' },
        { heading: 'Magna Carta\u2019s Real Historical Significance', body: 'Magna Carta (1215) is often popularly framed as an early "human rights" document, but its immediate purpose was much narrower — English barons forced King John to sign it specifically to protect THEIR OWN feudal privileges and limit arbitrary royal taxation and punishment, not to establish general rights for ordinary people. Its long-term significance came later, as the principle it established (that even a king is bound by law) was reinterpreted and expanded by later generations into a much broader constitutional concept.' },
        { heading: 'The Crusades Had Mixed, Often Contradictory Motives', body: 'The Crusades combined genuine religious conviction (recovering Christian holy sites) with more worldly motives — younger sons seeking land and status they wouldn\u2019t inherit at home, Italian city-states seeking lucrative trade access, and the Papacy consolidating religious authority across a fractured Western Christendom. Treating the Crusades as driven by a single, simple cause (either "pure faith" or "pure greed") misses this genuinely tangled mix of religious, economic and political motivation historians still actively debate.' }
      ],
      misconceptions: [
        { myth: 'The "Dark Ages" were a period of total cultural and intellectual stagnation.', reality: 'Modern historians largely reject this framing — the period saw major legal, architectural and institutional developments, even if classical scholarship declined from Rome\u2019s peak.' },
        { myth: 'Magna Carta was written to establish general rights for ordinary medieval people.', reality: 'It was written to protect the specific feudal privileges of rebellious barons — its broader "rule of law" significance was a later reinterpretation.' },
        { myth: 'The Crusades were motivated purely by religious belief, or purely by greed for land.', reality: 'Historians generally see a genuinely mixed set of religious, economic and political motives, varying by participant and crusade.' }
      ],
      expertNotes: [
        'Medieval historians increasingly avoid the term "Dark Ages" in academic work, viewing it as an outdated, overly simplistic Renaissance-era framing.',
        'Legal historians trace a direct line from Magna Carta\u2019s "rule of law" principle to much later constitutional documents, while being careful to note its original narrow intent.',
        'Economic historians point to the Black Death as a rare, clear case of a single event measurably accelerating the end of an entire economic system (feudalism).'
      ],
      examples: [{ q: 'What year was the Norman Conquest?', working: 'Battle of Hastings', answer: '1066' }, { q: 'What document limited King John\u2019s power in 1215?', working: 'Forced on him by rebellious barons', answer: 'Magna Carta' }]
    },
    earlymodern: {
      title: 'Early Modern History',
      intro: 'The Early Modern period (roughly 1500-1800) saw a rebirth of learning, religious upheaval, global exploration, and new political ideas.',
      origin: 'This period is often treated as the hinge between the medieval and modern worlds precisely because several independent developments converged within a couple of centuries of each other — the printing press (c.1440) enabled the rapid spread of both Renaissance humanist ideas and Reformation religious tracts, while advances in shipbuilding and navigation enabled the transoceanic voyages that connected the Americas to the rest of the world for the first time in human history.',
      sections: [
        { heading: 'The Printing Press as the Engine of Rapid Change', body: 'Gutenberg\u2019s printing press (c.1440) is arguably the single most consequential technology of this era — it made both the Renaissance\u2019s revival of classical texts and the Reformation\u2019s religious pamphlets vastly cheaper and faster to spread than hand-copied manuscripts ever allowed. Martin Luther\u2019s 95 Theses spread across Europe within weeks specifically BECAUSE printing existed — a Reformation-scale religious split would likely have unfolded far more slowly, if at all, in a manuscript-only world.' },
        { heading: 'The Reformation Was Political As Much As Theological', body: 'Luther\u2019s theological objections (particularly to the selling of indulgences) provided the spark, but the Reformation\u2019s rapid spread and staying power depended heavily on political rulers who found genuine political and financial advantage in breaking from Rome\u2019s authority and, in some cases, seizing Catholic Church lands and wealth within their territories. Religious conviction and political self-interest were deeply intertwined, not separate forces.' },
        { heading: 'European "Exploration" Had a Devastating Flip Side', body: 'From a European perspective this era is framed as "the Age of Exploration," but from the perspective of the Americas it was an era of conquest and catastrophic demographic collapse — diseases like smallpox, to which indigenous American populations had no prior immunity, killed an estimated 80-90% of the pre-contact population in the century following contact, making disease (not warfare) the single largest factor in the scale of the demographic catastrophe.' },
        { heading: 'The Enlightenment Directly Fuelled Revolution', body: 'Enlightenment thinkers (Locke\u2019s natural rights, Rousseau\u2019s social contract, Voltaire\u2019s challenge to religious authority) weren\u2019t just abstract philosophers — their ideas were directly cited and drawn on by the authors of the American Declaration of Independence and French revolutionary documents, making this intellectual movement a direct, traceable cause of the political revolutions that reshaped the following century.' }
      ],
      misconceptions: [
        { myth: 'The Reformation was a purely religious/theological dispute.', reality: 'Political rulers\u2019 own interests (seizing Church wealth and land, gaining independence from Rome\u2019s authority) were deeply intertwined with the religious motivations.' },
        { myth: 'European "exploration" of the Americas was mainly a story of discovery and adventure.', reality: 'From the indigenous perspective it caused catastrophic population collapse, overwhelmingly driven by introduced disease rather than direct conflict.' },
        { myth: 'The Enlightenment was abstract philosophy with little real-world political impact.', reality: 'Its ideas were directly cited in the founding documents of both the American and French Revolutions.' }
      ],
      expertNotes: [
        'Historians of the Reformation weigh political and economic motives alongside theological ones, rather than treating it as purely a religious dispute.',
        'Historical demographers now treat introduced disease, not military conquest, as the primary driver of indigenous American population collapse after 1492.',
        'Political historians trace direct textual lines from Locke and Rousseau\u2019s writing to specific passages in Enlightenment-era revolutionary documents.'
      ],
      examples: [{ q: 'Who started the Protestant Reformation in 1517?', working: 'Wrote the 95 Theses', answer: 'Martin Luther' }, { q: 'What period revived classical art and learning?', working: 'Began in Italy, 14th-17th century', answer: 'The Renaissance' }]
    },
    modern: {
      title: 'Modern History',
      intro: 'The Modern era (roughly 1800-1945) was defined by industrialisation, global war, and economic upheaval on a scale never seen before.',
      origin: 'This period is often studied as a story of ACCELERATION — technological, economic and military change that had unfolded over centuries in earlier eras now happened within single decades, driven initially by the Industrial Revolution\u2019s harnessing of steam power (from the 1760s onward), and culminating in two wars fought at an industrial scale and lethality no previous conflict had approached.',
      sections: [
        { heading: 'The Industrial Revolution Changed More Than Machinery', body: 'The shift to powered machinery didn\u2019t just make production faster — it fundamentally restructured society: populations moved from rural farms to urban factory cities at unprecedented speed, creating both immense new wealth and severe new problems (overcrowding, pollution, child labour) that existing social and legal systems weren\u2019t built to handle, directly driving the labour and social reform movements of the following century.' },
        { heading: 'WWI: Long-Term Tensions Meeting a Short-Term Trigger', body: 'The assassination of Archduke Franz Ferdinand is the EVENT that triggered WWI, but historians emphasise this was a spark, not the underlying cause — decades of competitive imperial expansion, an arms race between major powers, rigid military alliance systems (where one country\u2019s conflict automatically drew in its allies), and rising nationalism had built up tension that made SOME triggering event likely to cause a wide war; the specific assassination determined the timing and immediate cause, not the war\u2019s ultimate origin.' },
        { heading: 'Versailles\u2019 Harsh Terms and Their Long Shadow', body: 'The Treaty of Versailles (1919) imposed heavy reparations and territorial losses on Germany — while intended to prevent future German aggression, many historians argue its severity instead created the economic hardship and national resentment that Hitler and the Nazi party later exploited politically, making the treaty a genuine (if unintended and contested) contributing factor in WWII\u2019s origins roughly two decades later.' },
        { heading: 'The Great Depression Showed How Interconnected Economies Had Become', body: 'The 1929 Wall Street Crash triggering a WORLDWIDE depression (not just an American one) revealed just how interconnected the global economy had become through the preceding century of industrialisation and international trade and lending — economic shockwaves from one country\u2019s stock market could now rapidly transmit hardship across the entire globe, a genuinely new phenomenon at that scale.' }
      ],
      misconceptions: [
        { myth: 'The assassination of Franz Ferdinand was the sole cause of WWI.', reality: 'It was the immediate trigger — decades of alliance systems, militarism, imperial competition and nationalism were the deeper long-term causes that made a wide war likely.' },
        { myth: 'The Treaty of Versailles was universally seen as fair and reasonable at the time.', reality: 'Many contemporaries and later historians criticised its severity as counterproductive, arguing it fuelled the resentment that contributed to WWII.' },
        { myth: 'The Industrial Revolution was purely a story of technological progress.', reality: 'It also caused severe urban overcrowding, pollution and labour exploitation that took decades of reform movements to address.' }
      ],
      expertNotes: [
        'Historians consistently distinguish "trigger" events from underlying long-term causes when explaining major conflicts like WWI.',
        'Economic historians treat the Great Depression as a landmark case study in global economic interconnection and contagion.',
        'Historians studying WWII\u2019s origins routinely weigh the Treaty of Versailles as a contributing (not sole) factor alongside the Depression and specific political developments in 1930s Germany.'
      ],
      examples: [{ q: 'What triggered WWI in 1914?', working: 'Assassination in Sarajevo set off alliance obligations', answer: 'Assassination of Archduke Franz Ferdinand' }, { q: 'What treaty ended WWI?', working: 'Signed in 1919, harsh on Germany', answer: 'Treaty of Versailles' }]
    },
    twentiethcentury: {
      title: '20th Century World',
      intro: 'The second half of the 20th century was shaped by the ideological standoff of the Cold War and major movements for civil and political rights.',
      origin: 'The Cold War emerged directly from the aftermath of WWII — wartime allies the USA and Soviet Union had cooperated against a common enemy (Nazi Germany) but held fundamentally incompatible visions for the post-war world (capitalist democracy versus communist state control), and with both emerging as the two dominant global military powers (each soon possessing nuclear weapons), that ideological conflict played out globally for over four decades without the two superpowers ever directly fighting each other militarily.',
      sections: [
        { heading: 'Why It\u2019s Called a "Cold" War', body: 'The term "Cold War" specifically captures that the USA and USSR never directly fought each other militarily, despite intense hostility — instead, the conflict played out through "proxy wars" (conflicts in other countries, like Korea and Vietnam, where each superpower backed opposing sides), an arms race, espionage, and ideological competition for influence over other nations, precisely BECAUSE direct war between two nuclear powers risked mutual destruction on a scale neither side was willing to risk.' },
        { heading: 'The Cuban Missile Crisis: Closest to Direct Conflict', body: 'The 1962 Cuban Missile Crisis is treated by historians as the closest the Cold War ever came to becoming a direct, potentially nuclear war between the superpowers — the discovery of Soviet nuclear missiles stationed in Cuba, within easy striking range of the US mainland, led to a tense 13-day standoff resolved through secret diplomatic back-channels, not military action, precisely because both leaders (Kennedy and Khrushchev) recognised how catastrophically high the stakes had become.' },
        { heading: 'The Civil Rights Movement\u2019s Strategic Use of Media', body: 'The American Civil Rights Movement deliberately used peaceful, disciplined protest specifically because footage and photographs of nonviolent protesters facing violent resistance (police dogs, fire hoses) generated powerful public sympathy when broadcast nationally — this was a conscious strategic choice, not just a moral one, using the relatively new power of television media to build political pressure for legal change.' },
        { heading: 'Why the Berlin Wall\u2019s Fall Mattered So Much', body: 'The Berlin Wall\u2019s fall in 1989 mattered far beyond Germany because it was the most visible, concrete symbol of Europe\u2019s Cold War division — its collapse both reflected and accelerated the broader unravelling of Soviet control across Eastern Europe that culminated in the Soviet Union\u2019s own dissolution in 1991, marking the definitive end of the Cold War era.' }
      ],
      misconceptions: [
        { myth: 'The Cold War means the USA and USSR fought each other directly in wars.', reality: 'They never fought each other directly — the conflict played out through proxy wars, an arms race, and ideological competition specifically to avoid direct nuclear confrontation.' },
        { myth: 'The Civil Rights Movement\u2019s use of peaceful protest was purely about moral principle.', reality: 'It was also a deliberate strategic choice, since footage of peaceful protesters facing violence generated powerful public and political sympathy via television.' },
        { myth: 'The Berlin Wall\u2019s fall was an isolated event specific only to Germany.', reality: 'It both symbolised and accelerated the wider collapse of Soviet control across Eastern Europe, leading to the USSR\u2019s dissolution.' }
      ],
      expertNotes: [
        'Cold War historians specifically study proxy conflicts (Korea, Vietnam, Afghanistan) as the primary arena where superpower rivalry actually played out militarily.',
        'Media historians treat the Civil Rights Movement as an early, influential case study in using television coverage to build a political and moral case for change.',
        'Historians treat 1989-1991 as a single continuous unravelling, not isolated events, when explaining the Cold War\u2019s end.'
      ],
      examples: [{ q: 'What crisis in 1962 nearly caused nuclear war?', working: 'Soviet missiles discovered in Cuba', answer: 'The Cuban Missile Crisis' }, { q: 'What wall symbolised Cold War division, falling in 1989?', working: 'Divided East and West Berlin', answer: 'The Berlin Wall' }]
    },
    skills: {
      title: 'Historical Skills',
      intro: 'GCSE History marks aren\u2019t just about facts — you need to evaluate sources, explain causation, and understand why interpretations of the past can differ.',
      origin: 'The formal study of HOW we know about the past (rather than just what happened) is called historiography, and it developed substantially in the 19th-20th centuries as historians increasingly recognised that all historical accounts — even ones based on real evidence — are shaped by the perspective, available sources, and questions of whoever is writing them, which is precisely why GCSE History assesses source evaluation and interpretation as core skills, not just factual recall.',
      sections: [
        { heading: 'Primary vs Secondary: Proximity to the Event, Not Just Age', body: 'The primary/secondary distinction is about PROXIMITY to the event (was this created at the time, by someone with direct knowledge?), not simply how old a source is — a documentary made in 2020 about events from 2020 could still count as closer to primary if made by direct participants, while a history book about ancient Rome written in the 1800s is still a secondary source, despite being "old," because its author wasn\u2019t there.' },
        { heading: 'Reliability Is Not the Same as Usefulness', body: 'A heavily biased source (a wartime propaganda poster, a politician\u2019s self-serving memoir) can be UNRELIABLE for establishing objective facts, yet still extremely USEFUL as evidence of the attitudes, fears or propaganda techniques of that time and place — historians are trained to extract this second kind of value even from sources they don\u2019t trust at face value, rather than simply discarding biased sources as worthless.' },
        { heading: 'Causation Requires Explaining HOW Causes Connect', body: 'A strong causation answer doesn\u2019t just list several causes of an event — it explains HOW those causes connected and built on each other to make the event more likely, distinguishing long-term underlying tensions (that built for years) from short-term triggers (the immediate spark). This "how do these link together" explanatory step is specifically what separates a top-band answer from a merely descriptive list of causes.' },
        { heading: 'Why Legitimate Historical Interpretations Can Differ', body: 'Two well-informed historians can honestly disagree about the same event because they may draw on different available sources, ask different questions (economic causes vs social causes vs individual leaders\u2019 choices), or bring different theoretical frameworks to the same evidence — this doesn\u2019t mean "history is just opinion," but it does mean interpretation involves genuine, defensible scholarly judgement, not just assembling agreed-upon facts.' }
      ],
      misconceptions: [
        { myth: 'An old source is automatically a primary source, and a recent one is automatically secondary.', reality: 'The distinction is about proximity to the event (were they there, at the time?), not the source\u2019s age.' },
        { myth: 'A biased or unreliable source has no historical value and should be dismissed.', reality: 'A biased source can still be genuinely useful as evidence of the attitudes or propaganda techniques of its time, even if unreliable for objective facts.' },
        { myth: 'Historians disagreeing about an event means the facts are unknowable or "just opinion."', reality: 'Legitimate disagreement usually reflects different evidence, questions or frameworks being applied to broadly agreed underlying facts.' }
      ],
      expertNotes: [
        'Professional historians are trained to extract value from biased sources as evidence of attitudes, even while explicitly flagging their unreliability for objective fact.',
        'Exam mark schemes specifically reward explaining HOW causes connect and build on each other, not just identifying and listing separate causes.',
        'Historiography (the study of how historical interpretation itself changes over time) is a recognised academic field distinct from history itself.'
      ],
      examples: [{ q: 'What is a primary source?', working: 'Created at the time of the event', answer: 'Evidence created at the time of the event' }, { q: 'What is a long-term cause?', working: 'Builds up gradually, unlike a sudden trigger', answer: 'An underlying factor building up over years or decades' }]
    }
  };

  var FORMULAS = [
    { topic: 'Skills', name: 'Source reliability check', formula: 'Consider: Who? Why? When? How close to the event?', when: 'Evaluating any historical source.', example: 'A soldier\u2019s diary is reliable for his own experience, but may be biased about the wider war.', tip: 'A source can be useful even if biased — bias itself can reveal attitudes of the time.' },
    { topic: 'Skills', name: 'Causation: long vs short-term', formula: 'Long-term = builds over years | Short-term = immediate trigger', when: 'Explaining why an event happened.', example: 'WWI: long-term = alliances & militarism; short-term = assassination of Franz Ferdinand.', tip: 'Strong answers explain HOW causes link together, not just list them.' },
    { topic: 'Skills', name: 'PEEL paragraph structure', formula: 'Point \u2192 Evidence \u2192 Explain \u2192 Link', when: 'Writing extended History exam answers.', example: 'Point: Feudalism weakened after the Black Death. Evidence: labour shortages... Explain: peasants could demand pay... Link: this contributed to the end of serfdom.', tip: 'Always link back to the question at the end of each paragraph.' },
    { topic: 'Timeline', name: 'Ancient era', formula: '~3000 BCE \u2013 500 CE', when: 'Egypt, Mesopotamia, Greece, Rome.', example: 'Roman Empire fell in the West in 476 CE.', tip: 'Use BCE/CE, not BC/AD, in modern academic writing.' },
    { topic: 'Timeline', name: 'Medieval era', formula: '~500 \u2013 1500 CE', when: 'Feudalism, Crusades, Black Death, Magna Carta.', example: 'Norman Conquest: 1066. Black Death: 1347-1351.', tip: 'The medieval period is also called "The Middle Ages".' },
    { topic: 'Timeline', name: 'Early Modern era', formula: '~1500 \u2013 1800 CE', when: 'Renaissance, Reformation, exploration, Enlightenment.', example: 'Martin Luther\u2019s 95 Theses: 1517. Columbus reaches Americas: 1492.', tip: 'This era bridges the medieval world and the modern industrial age.' },
    { topic: 'Timeline', name: 'Modern era', formula: '~1800 \u2013 1945', when: 'Industrial Revolution, WWI, WWII, Great Depression.', example: 'WWI: 1914-1918. WWII: 1939-1945.', tip: 'The two World Wars are the defining events of this period.' },
    { topic: 'Timeline', name: '20th Century World', formula: '~1945 \u2013 1991 (Cold War era)', when: 'Cold War, Civil Rights, decolonisation.', example: 'Cuban Missile Crisis: 1962. Berlin Wall falls: 1989.', tip: 'The Cold War ended with the Soviet Union\u2019s collapse in 1991.' }
  ];

  root.LearningHistory = {
    generate: generate, generateForLevel: generateForLevel, generateLevelSet: generateLevelSet, generatePlacementSet: generatePlacementSet,
    levelLabel: levelLabel, gradeFromLevel: gradeFromLevel, levelFromScore: levelFromScore, strongestWeakest: strongestWeakest,
    QT_TYPES: QT_TYPES, QT_DIFFICULTIES: QT_DIFFICULTIES, QT_LENGTHS: QT_LENGTHS,
    buildQuickTest: buildQuickTest, generateDailyChallenge: generateDailyChallenge, levelToTier: qtLevelToTier,
    checkAnswer: checkAnswer, LESSONS: LESSONS, FORMULAS: FORMULAS,
    TOPICS: [
      { key: 'ancient', label: 'Ancient Civilisations', desc: 'Egypt, Greece, Rome & early trade' },
      { key: 'medieval', label: 'Medieval History', desc: 'Feudalism, Black Death & Magna Carta' },
      { key: 'earlymodern', label: 'Early Modern History', desc: 'Renaissance, Reformation & exploration' },
      { key: 'modern', label: 'Modern History', desc: 'Industrial Revolution & the World Wars' },
      { key: 'twentiethcentury', label: '20th Century World', desc: 'Cold War, Civil Rights & decolonisation' },
      { key: 'skills', label: 'Historical Skills', desc: 'Sources, causation & interpretation' }
    ]
  };
})(window);
